#!/bin/bash
# This script adds aliases for all entity types
# Exit on error
set -e

# Function to add alias pair with specified entity type
add_alias() {
    local entity_type=$1
    local canonical=$2
    local alias=$3
    echo "Adding $entity_type alias: $canonical ↔ $alias"
    cargo run --bin manage_aliases -- add --canonical "$canonical" --alias "$alias" --entity-type "$entity_type" --source "pattern" --confidence 0.95
}

echo "==== ADDING PERSON ALIASES ===="

# -------- FORTUNE 500 & GLOBAL 500 LEADERS --------
# Tech CEOs
add_alias "person" "Tim Cook" "Timothy Cook"
add_alias "person" "Tim Cook" "Timothy D. Cook"
add_alias "person" "Satya Nadella" "Satya N. Nadella"
add_alias "person" "Sundar Pichai" "Sundar Pichai Sundararajan"
add_alias "person" "Andy Jassy" "Andrew Jassy"
add_alias "person" "Andy Jassy" "Andrew R. Jassy"
add_alias "person" "Mark Zuckerberg" "Mark E. Zuckerberg"
add_alias "person" "Jensen Huang" "Jen-Hsun Huang"
add_alias "person" "Jensen Huang" "黄仁勋"
add_alias "person" "Pat Gelsinger" "Patrick Gelsinger"
add_alias "person" "Pat Gelsinger" "Patrick P. Gelsinger"
add_alias "person" "Lisa Su" "Lisa T. Su"
add_alias "person" "Lisa Su" "蘇姿丰"
add_alias "person" "Chuck Robbins" "Charles Robbins"
add_alias "person" "Chuck Robbins" "Charles H. Robbins"
add_alias "person" "Marc Benioff" "Marc R. Benioff"

# Retail & Consumer CEOs
add_alias "person" "Doug McMillon" "C. Douglas McMillon"
add_alias "person" "Brian Cornell" "Brian C. Cornell"
add_alias "person" "Craig Jelinek" "W. Craig Jelinek"
add_alias "person" "Marvin Ellison" "Marvin R. Ellison"
add_alias "person" "James Quincey" "Jim Quincey"
add_alias "person" "Howard Schultz" "Howard D. Schultz"
add_alias "person" "Chris Kempczinski" "Christopher Kempczinski"
add_alias "person" "Chris Kempczinski" "Christopher J. Kempczinski"
add_alias "person" "Karen Lynch" "Karen S. Lynch"
add_alias "person" "Rosalind Brewer" "Rosalind G. Brewer"

# Financial CEOs
add_alias "person" "Jamie Dimon" "James Dimon"
add_alias "person" "Brian Moynihan" "Brian T. Moynihan"
add_alias "person" "Charles Scharf" "Charles W. Scharf"
add_alias "person" "David Solomon" "David M. Solomon"
add_alias "person" "James Gorman" "James P. Gorman"
add_alias "person" "Stephen Squeri" "Stephen J. Squeri"
add_alias "person" "Alfred Kelly" "Alfred F. Kelly Jr."
add_alias "person" "Larry Fink" "Laurence D. Fink"
add_alias "person" "Warren Buffett" "Warren E. Buffett"

# Healthcare CEOs
add_alias "person" "Joaquin Duato" "Joaquin Duato de la Sierra"
add_alias "person" "Robert Davis" "Robert M. Davis"
add_alias "person" "Richard Gonzalez" "Richard A. Gonzalez"
add_alias "person" "David Ricks" "David A. Ricks"
add_alias "person" "Robert Bradway" "Robert A. Bradway"
add_alias "person" "Robert Ford" "Robert B. Ford"
add_alias "person" "Geoff Martha" "Geoffrey S. Martha"
add_alias "person" "Sam Hazen" "Samuel N. Hazen"

# Energy & Industry CEOs
add_alias "person" "Darren Woods" "Darren W. Woods"
add_alias "person" "Michael Wirth" "Michael K. Wirth"
add_alias "person" "Ryan Lance" "Ryan M. Lance"
add_alias "person" "John Stankey" "John T. Stankey"
add_alias "person" "Jim Farley" "James D. Farley Jr."
add_alias "person" "Mary Barra" "Mary T. Barra"
add_alias "person" "David Calhoun" "David L. Calhoun"
add_alias "person" "Jim Umpleby" "D. James Umpleby III"
add_alias "person" "Greg Hayes" "Gregory J. Hayes"
add_alias "person" "Larry Culp" "H. Lawrence Culp Jr."

# International Business Leaders
add_alias "person" "Bernard Arnault" "Bernard Jean Étienne Arnault"
add_alias "person" "Masayoshi Son" "Son Masayoshi"
add_alias "person" "Masayoshi Son" "孫正義"
add_alias "person" "Carlos Slim" "Carlos Slim Helú"
add_alias "person" "Mukesh Ambani" "Mukesh Dhirubhai Ambani"
add_alias "person" "Zhong Shanshan" "钟睒睒"
add_alias "person" "Amancio Ortega" "Amancio Ortega Gaona"
add_alias "person" "Tadashi Yanai" "Yanai Tadashi"
add_alias "person" "Tadashi Yanai" "柳井正"
add_alias "person" "Francoise Bettencourt Meyers" "Françoise Bettencourt Meyers"
add_alias "person" "Wang Wei" "王卫"
add_alias "person" "Ma Huateng" "Pony Ma"
add_alias "person" "Ma Huateng" "马化腾"
add_alias "person" "Jack Ma" "Ma Yun"
add_alias "person" "Jack Ma" "马云"
add_alias "person" "Colin Zheng Huang" "Huang Zheng"
add_alias "person" "Colin Zheng Huang" "黄峥"
add_alias "person" "Lei Jun" "雷军"
add_alias "person" "Zhang Yiming" "张一鸣"
add_alias "person" "Lakshmi Mittal" "Lakshmi Niwas Mittal"
add_alias "person" "Oleg Deripaska" "Oleg Vladimirovich Deripaska"
add_alias "person" "Oleg Deripaska" "Олег Владимирович Дерипаска"

# -------- POLITICAL LEADERS --------
# US Presidents/Leaders
add_alias "person" "Joe Biden" "Joseph Biden"
add_alias "person" "Joe Biden" "President Biden"
add_alias "person" "Joe Biden" "Joseph R. Biden"
add_alias "person" "Joe Biden" "Joseph Robinette Biden Jr."
add_alias "person" "Kamala Harris" "Kamala Devi Harris"
add_alias "person" "Donald Trump" "Donald J. Trump"
add_alias "person" "Donald Trump" "Donald John Trump"
add_alias "person" "Donald Trump" "President Trump"
add_alias "person" "Barack Obama" "Barack H. Obama"
add_alias "person" "Barack Obama" "Barack Hussein Obama"
add_alias "person" "Barack Obama" "President Obama"
add_alias "person" "George Bush" "George W. Bush"
add_alias "person" "George Bush" "George Walker Bush"
add_alias "person" "George Bush" "President Bush"
add_alias "person" "Bill Clinton" "William Jefferson Clinton"
add_alias "person" "Bill Clinton" "William J. Clinton"
add_alias "person" "Bill Clinton" "President Clinton"
add_alias "person" "Nancy Pelosi" "Nancy Patricia Pelosi"
add_alias "person" "Mike Pence" "Michael R. Pence"
add_alias "person" "Mike Pence" "Michael Richard Pence"
add_alias "person" "Hillary Clinton" "Hillary Rodham Clinton"
add_alias "person" "Mitch McConnell" "Addison Mitchell McConnell Jr."
add_alias "person" "Chuck Schumer" "Charles Ellis Schumer"
add_alias "person" "Kevin McCarthy" "Kevin Owen McCarthy"
add_alias "person" "Hakeem Jeffries" "Hakeem Sekou Jeffries"
add_alias "person" "Janet Yellen" "Janet Louise Yellen"
add_alias "person" "Anthony Fauci" "Anthony Stephen Fauci"
add_alias "person" "John Roberts" "John Glover Roberts Jr."

# International Leaders
add_alias "person" "Xi Jinping" "习近平"
add_alias "person" "Vladimir Putin" "Vladimir Vladimirovich Putin"
add_alias "person" "Vladimir Putin" "Владимир Владимирович Путин"
add_alias "person" "Emmanuel Macron" "Emmanuel Jean-Michel Frédéric Macron"
add_alias "person" "Angela Merkel" "Angela Dorothea Merkel"
add_alias "person" "Boris Johnson" "Alexander Boris de Pfeffel Johnson"
add_alias "person" "Narendra Modi" "नरेंद्र दामोदरदास मोदी"
add_alias "person" "Justin Trudeau" "Justin Pierre James Trudeau"
add_alias "person" "Fumio Kishida" "Kishida Fumio"
add_alias "person" "Fumio Kishida" "岸田文雄"
add_alias "person" "Sheikh Mohammed bin Zayed Al Nahyan" "محمد بن زايد آل نهيان"
add_alias "person" "Mohammed bin Salman" "Mohammed bin Salman Al Saud"
add_alias "person" "Mohammed bin Salman" "محمد بن سلمان آل سعود"
add_alias "person" "Abdel Fattah el-Sisi" "Abdel Fattah Saeed Hussein Khalil el-Sisi"
add_alias "person" "Abdel Fattah el-Sisi" "عبد الفتاح سعيد حسين خليل السيسي"
add_alias "person" "Recep Tayyip Erdoğan" "Recep Tayyip Erdogan"
add_alias "person" "Recep Tayyip Erdoğan" "رجب طیب اردوغان"
add_alias "person" "Jair Bolsonaro" "Jair Messias Bolsonaro"
add_alias "person" "Luiz Inácio Lula da Silva" "Luiz Inacio Lula da Silva"
add_alias "person" "Luiz Inácio Lula da Silva" "Lula"
add_alias "person" "Cyril Ramaphosa" "Matamela Cyril Ramaphosa"
add_alias "person" "Andrés Manuel López Obrador" "Andres Manuel Lopez Obrador"
add_alias "person" "Andrés Manuel López Obrador" "AMLO"
add_alias "person" "Anthony Albanese" "Anthony Norman Albanese"
add_alias "person" "Volodymyr Zelensky" "Volodymyr Oleksandrovych Zelensky"
add_alias "person" "Volodymyr Zelensky" "Володимир Олександрович Зеленський"
add_alias "person" "Alexander Lukashenko" "Alexander Grigoryevich Lukashenko"
add_alias "person" "Alexander Lukashenko" "Александр Григорьевич Лукашенко"
add_alias "person" "Kim Jong-un" "Kim Jong Un"
add_alias "person" "Kim Jong-un" "김정은"
add_alias "person" "Yoon Suk Yeol" "Yoon Suk-yeol"
add_alias "person" "Yoon Suk Yeol" "윤석열"
add_alias "person" "Ursula von der Leyen" "Ursula Gertrud von der Leyen"

# -------- DRUPAL DEVELOPERS --------
add_alias "person" "Angela Byron" "webchick"
add_alias "person" "Gábor Hojtsy" "Gabor Hojtsy"
add_alias "person" "Nathaniel Catchpole" "catch"
add_alias "person" "Alex Pott" "alexpott"
add_alias "person" "Daniel Wehner" "dawehner"
add_alias "person" "Tim Plunkett" "timplunkett"
add_alias "person" "Jess Myrbo" "xjm"
add_alias "person" "Larry Garfield" "Crell"
add_alias "person" "Moshe Weitzman" "moshe weitzman"
add_alias "person" "Jeff Geerling" "geerlingguy"
add_alias "person" "Angie Byron" "Angela Byron"
add_alias "person" "Alex Bronstein" "effulgentsia"
add_alias "person" "David Rothstein" "drupol"

# -------- AI DEVELOPERS & EVANGELISTS --------
add_alias "person" "Geoffrey Hinton" "Geoffrey Everest Hinton"
add_alias "person" "Yann LeCun" "Yann Andre LeCun"
add_alias "person" "Andrew Ng" "Andrew Y. Ng"
add_alias "person" "Fei-Fei Li" "李飞飞"
add_alias "person" "Ian Goodfellow" "Ian J. Goodfellow"
add_alias "person" "Sam Altman" "Samuel H. Altman"
add_alias "person" "Ilya Sutskever" "Илья Суцкевер"
add_alias "person" "Jeff Dean" "Jeffrey Adgate Dean"
add_alias "person" "Kai-Fu Lee" "李开复"
add_alias "person" "Joy Buolamwini" "Joy Adowaa Buolamwini"
add_alias "person" "Gary Marcus" "Gary F. Marcus"
add_alias "person" "Stuart Russell" "Stuart J. Russell"
add_alias "person" "Ray Kurzweil" "Raymond Kurzweil"
add_alias "person" "Max Tegmark" "Max Erik Tegmark"
add_alias "person" "Nick Bostrom" "Niklas Boström"
add_alias "person" "Eliezer Yudkowsky" "Eliezer Shlomo Yudkowsky"
add_alias "person" "Rodney Brooks" "Rodney Allen Brooks"
add_alias "person" "Oriol Vinyals" "Oriol Vinyals Fortuny"
add_alias "person" "Melanie Mitchell" "Melanie A. Mitchell"
add_alias "person" "Sebastian Thrun" "Sebastian Burkhard Thrun"
add_alias "person" "Sam Harris" "Samuel B. Harris"
add_alias "person" "Ben Goertzel" "Benjamin Goertzel"
add_alias "person" "Lex Fridman" "Alexei Fridman"
add_alias "person" "Lex Fridman" "Алексей Фридман"

# -------- HISTORICAL FIGURES --------
# Political Leaders
add_alias "person" "Franklin D. Roosevelt" "Franklin Delano Roosevelt"
add_alias "person" "Winston Churchill" "Sir Winston Leonard Spencer Churchill"
add_alias "person" "Mahatma Gandhi" "Mohandas Karamchand Gandhi"
add_alias "person" "Mahatma Gandhi" "महात्मा गांधी"
add_alias "person" "Nelson Mandela" "Nelson Rolihlahla Mandela"
add_alias "person" "Martin Luther King Jr." "Michael King Jr."
add_alias "person" "Mao Zedong" "Mao Tse-tung"
add_alias "person" "Mao Zedong" "毛泽东"
add_alias "person" "Joseph Stalin" "Joseph Vissarionovich Stalin"
add_alias "person" "Joseph Stalin" "Иосиф Виссарионович Сталин"
add_alias "person" "Joseph Stalin" "Ioseb Besarionis dzе Jughashvili"
add_alias "person" "Napoleon Bonaparte" "Napoléon Bonaparte"
add_alias "person" "Napoleon Bonaparte" "Napoleon I"
add_alias "person" "Queen Elizabeth II" "Elizabeth Alexandra Mary Windsor"
add_alias "person" "Benito Mussolini" "Benito Amilcare Andrea Mussolini"
add_alias "person" "Julius Caesar" "Gaius Julius Caesar"
add_alias "person" "Augustus" "Gaius Octavius"
add_alias "person" "Augustus" "Augustus Caesar"
add_alias "person" "Cleopatra" "Cleopatra VII Philopator"
add_alias "person" "Alexander the Great" "Alexander III of Macedon"
add_alias "person" "Charlemagne" "Charles the Great"
add_alias "person" "Genghis Khan" "Temüjin"
add_alias "person" "Genghis Khan" "Чингис Хаан"
add_alias "person" "Catherine the Great" "Catherine II"
add_alias "person" "Catherine the Great" "Екатерина II Великая"
add_alias "person" "Peter the Great" "Peter I"
add_alias "person" "Peter the Great" "Пётр Великий"

# Scientists & Inventors
add_alias "person" "Isaac Newton" "Sir Isaac Newton"
add_alias "person" "Marie Curie" "Maria Skłodowska Curie"
add_alias "person" "Marie Curie" "Maria Skłodowska"
add_alias "person" "Nikola Tesla" "Никола Тесла"
add_alias "person" "Charles Darwin" "Charles Robert Darwin"
add_alias "person" "Ada Lovelace" "Augusta Ada King, Countess of Lovelace" 
add_alias "person" "Ada Lovelace" "Ada Byron"
add_alias "person" "Thomas Edison" "Thomas Alva Edison"
add_alias "person" "Alan Turing" "Alan Mathison Turing"
add_alias "person" "Stephen Hawking" "Stephen William Hawking"
add_alias "person" "Louis Pasteur" "Louis Jean Pasteur"
add_alias "person" "James Watson" "James Dewey Watson"
add_alias "person" "Francis Crick" "Francis Harry Compton Crick"
add_alias "person" "Rosalind Franklin" "Rosalind Elsie Franklin"
add_alias "person" "Katherine Johnson" "Katherine Goble Johnson"
add_alias "person" "Carl Sagan" "Carl Edward Sagan"
add_alias "person" "Ibn al-Haytham" "Alhacen"
add_alias "person" "Ibn al-Haytham" "أبو علي، الحسن بن الحسن بن الهيثم"
add_alias "person" "Emmy Noether" "Amalie Emmy Noether"

# Writers, Artists & Philosophers
add_alias "person" "Leonardo da Vinci" "Leonardo di ser Piero da Vinci"
add_alias "person" "Aristotle" "Aristotélēs"
add_alias "person" "Aristotle" "Ἀριστοτέλης"
add_alias "person" "Plato" "Plátōn"
add_alias "person" "Plato" "Πλάτων"
add_alias "person" "Socrates" "Sōkrátēs"
add_alias "person" "Socrates" "Σωκράτης"
add_alias "person" "Confucius" "Kong Fuzi"
add_alias "person" "Confucius" "Kongzi"
add_alias "person" "Confucius" "孔子"
add_alias "person" "Vincent van Gogh" "Vincent Willem van Gogh"
add_alias "person" "Pablo Picasso" "Pablo Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Mártir Patricio Clito Ruíz y Picasso"
add_alias "person" "Fyodor Dostoevsky" "Fyodor Mikhailovich Dostoevsky"
add_alias "person" "Fyodor Dostoevsky" "Фёдор Михайлович Достоевский"
add_alias "person" "Michelangelo" "Michelangelo di Lodovico Buonarroti Simoni"
add_alias "person" "Wolfgang Amadeus Mozart" "Johannes Chrysostomus Wolfgangus Theophilus Mozart"
add_alias "person" "Wolfgang Amadeus Mozart" "Wolfgang Amadé Mozart"
add_alias "person" "Frida Kahlo" "Magdalena Carmen Frida Kahlo y Calderón"
add_alias "person" "Virginia Woolf" "Adeline Virginia Woolf"
add_alias "person" "Virginia Woolf" "Virginia Stephen"
add_alias "person" "Gabriel García Márquez" "Gabriel José García Márquez"
add_alias "person" "Gabriel García Márquez" "Gabo"
add_alias "person" "Leo Tolstoy" "Count Lev Nikolayevich Tolstoy"
add_alias "person" "Leo Tolstoy" "Лев Николаевич Толстой"

# Business & Tech Historical Figures
add_alias "person" "Steve Jobs" "Steven Jobs"
add_alias "person" "Steve Jobs" "Steven P. Jobs"
add_alias "person" "Bill Gates" "William Gates"
add_alias "person" "Bill Gates" "William H. Gates"
add_alias "person" "Jeff Bezos" "Jeffrey Bezos"
add_alias "person" "Jeff Bezos" "Jeffrey P. Bezos"
add_alias "person" "Elon Musk" "Elon R. Musk"
add_alias "person" "John D. Rockefeller" "John Davison Rockefeller"
add_alias "person" "Walt Disney" "Walter Elias Disney"
add_alias "person" "J.P. Morgan" "John Pierpont Morgan"
add_alias "person" "Oprah Winfrey" "Oprah Gail Winfrey"
add_alias "person" "Sam Walton" "Samuel Moore Walton"
add_alias "person" "Ray Kroc" "Raymond Albert Kroc"

echo "==== ADDING PRODUCT ALIASES ===="

# Apple Products
add_alias "product" "iPhone" "Apple iPhone"
add_alias "product" "iPhone 15" "Apple iPhone 15"
add_alias "product" "iPhone 15 Pro" "Apple iPhone 15 Pro"
add_alias "product" "iPhone 15 Pro Max" "Apple iPhone 15 Pro Max"
add_alias "product" "iPhone 14" "Apple iPhone 14"
add_alias "product" "iPhone 14 Pro" "Apple iPhone 14 Pro"
add_alias "product" "iPhone SE" "Apple iPhone SE"
add_alias "product" "MacBook" "Apple MacBook"
add_alias "product" "MacBook Pro" "Apple MacBook Pro"
add_alias "product" "MacBook Air" "Apple MacBook Air"
add_alias "product" "iPad" "Apple iPad"
add_alias "product" "iPad Pro" "Apple iPad Pro"
add_alias "product" "iPad Air" "Apple iPad Air"
add_alias "product" "iPad mini" "Apple iPad mini"
add_alias "product" "Apple Watch" "Apple Watch Series"
add_alias "product" "Apple Watch Ultra" "Apple Watch Ultra"
add_alias "product" "AirPods" "Apple AirPods"
add_alias "product" "AirPods Pro" "Apple AirPods Pro"
add_alias "product" "AirPods Max" "Apple AirPods Max"
add_alias "product" "Apple TV" "Apple TV 4K"
add_alias "product" "HomePod" "Apple HomePod"
add_alias "product" "HomePod mini" "Apple HomePod mini"
add_alias "product" "Mac Studio" "Apple Mac Studio"
add_alias "product" "Mac Pro" "Apple Mac Pro"
add_alias "product" "Mac mini" "Apple Mac mini"
add_alias "product" "iMac" "Apple iMac"
add_alias "product" "Magic Keyboard" "Apple Magic Keyboard"
add_alias "product" "Magic Mouse" "Apple Magic Mouse"
add_alias "product" "Magic Trackpad" "Apple Magic Trackpad"

# Microsoft Products
add_alias "product" "Surface" "Microsoft Surface"
add_alias "product" "Surface Pro" "Microsoft Surface Pro"
add_alias "product" "Surface Laptop" "Microsoft Surface Laptop" 
add_alias "product" "Surface Book" "Microsoft Surface Book"
add_alias "product" "Surface Studio" "Microsoft Surface Studio"
add_alias "product" "Surface Go" "Microsoft Surface Go"
add_alias "product" "Windows" "Microsoft Windows"
add_alias "product" "Windows 11" "Microsoft Windows 11"
add_alias "product" "Windows 10" "Microsoft Windows 10"
add_alias "product" "Office" "Microsoft Office"
add_alias "product" "Office 365" "Microsoft Office 365"
add_alias "product" "Microsoft 365" "M365"
add_alias "product" "Xbox" "Microsoft Xbox"
add_alias "product" "Xbox Series X" "Microsoft Xbox Series X"
add_alias "product" "Xbox Series S" "Microsoft Xbox Series S"
add_alias "product" "Xbox One" "Microsoft Xbox One"
add_alias "product" "Word" "Microsoft Word"
add_alias "product" "Excel" "Microsoft Excel"
add_alias "product" "PowerPoint" "Microsoft PowerPoint"
add_alias "product" "Outlook" "Microsoft Outlook"
add_alias "product" "Teams" "Microsoft Teams"
add_alias "product" "SharePoint" "Microsoft SharePoint"
add_alias "product" "OneDrive" "Microsoft OneDrive"
add_alias "product" "Azure" "Microsoft Azure"
add_alias "product" "Visual Studio" "Microsoft Visual Studio"
add_alias "product" "Visual Studio Code" "VS Code"
add_alias "product" "Bing" "Microsoft Bing"
add_alias "product" "Microsoft Edge" "Edge browser"
add_alias "product" "HoloLens" "Microsoft HoloLens"
add_alias "product" "Copilot" "Microsoft Copilot"
add_alias "product" "GitHub Copilot" "Microsoft GitHub Copilot"

# Google Products
add_alias "product" "Pixel" "Google Pixel"
add_alias "product" "Pixel 8" "Google Pixel 8"
add_alias "product" "Pixel 8 Pro" "Google Pixel 8 Pro"
add_alias "product" "Pixel 7" "Google Pixel 7"
add_alias "product" "Pixel Fold" "Google Pixel Fold"
add_alias "product" "Pixel Tablet" "Google Pixel Tablet"
add_alias "product" "Android" "Google Android"
add_alias "product" "Chrome" "Google Chrome"
add_alias "product" "Chrome OS" "Google Chrome OS"
add_alias "product" "Chromebook" "Google Chromebook"
add_alias "product" "Nest" "Google Nest"
add_alias "product" "Nest Hub" "Google Nest Hub"
add_alias "product" "Nest Thermostat" "Google Nest Thermostat"
add_alias "product" "Nest Doorbell" "Google Nest Doorbell"
add_alias "product" "Google Home" "Home speaker"
add_alias "product" "Gmail" "Google Mail"
add_alias "product" "Google Docs" "Docs"
add_alias "product" "Google Sheets" "Sheets"
add_alias "product" "Google Slides" "Slides"
add_alias "product" "Google Drive" "Drive"
add_alias "product" "Google Maps" "Maps"
add_alias "product" "Google Meet" "Meet"
add_alias "product" "Google Photos" "Photos"
add_alias "product" "Google Cloud" "GCP"
add_alias "product" "Google Cloud Platform" "GCP"
add_alias "product" "Google Workspace" "G Suite"
add_alias "product" "Google TV" "Google TV"
add_alias "product" "Google Search" "Google"
add_alias "product" "YouTube" "Google YouTube"
add_alias "product" "YouTube Premium" "YouTube Red"
add_alias "product" "YouTube TV" "YouTube Television"
add_alias "product" "Google Bard" "Bard AI"
add_alias "product" "Google Gemini" "Gemini AI"

# Samsung Products
add_alias "product" "Galaxy" "Samsung Galaxy"
add_alias "product" "Galaxy S23" "Samsung Galaxy S23"
add_alias "product" "Galaxy S23 Ultra" "Samsung Galaxy S23 Ultra"
add_alias "product" "Galaxy Z Fold" "Samsung Galaxy Z Fold"
add_alias "product" "Galaxy Z Flip" "Samsung Galaxy Z Flip"
add_alias "product" "Galaxy Tab" "Samsung Galaxy Tab"
add_alias "product" "Galaxy Watch" "Samsung Galaxy Watch"
add_alias "product" "Galaxy Buds" "Samsung Galaxy Buds"
add_alias "product" "QLED TV" "Samsung QLED TV"
add_alias "product" "Neo QLED" "Samsung Neo QLED"
add_alias "product" "The Frame" "Samsung The Frame"
add_alias "product" "Bespoke" "Samsung Bespoke"
add_alias "product" "Family Hub" "Samsung Family Hub"

# Amazon Products
add_alias "product" "Echo" "Amazon Echo"
add_alias "product" "Echo Dot" "Amazon Echo Dot"
add_alias "product" "Echo Show" "Amazon Echo Show"
add_alias "product" "Echo Studio" "Amazon Echo Studio"
add_alias "product" "Alexa" "Amazon Alexa"
add_alias "product" "Fire TV" "Amazon Fire TV"
add_alias "product" "Fire TV Stick" "Amazon Fire TV Stick"
add_alias "product" "Kindle" "Amazon Kindle"
add_alias "product" "Kindle Paperwhite" "Amazon Kindle Paperwhite"
add_alias "product" "Kindle Oasis" "Amazon Kindle Oasis"
add_alias "product" "Fire Tablet" "Amazon Fire Tablet"
add_alias "product" "Ring" "Amazon Ring"
add_alias "product" "Ring Doorbell" "Amazon Ring Doorbell"
add_alias "product" "Blink" "Amazon Blink"
add_alias "product" "Amazon Prime" "Prime"
add_alias "product" "Prime Video" "Amazon Prime Video"
add_alias "product" "Amazon Music" "Prime Music"
add_alias "product" "AWS" "Amazon Web Services"
add_alias "product" "Amazon S3" "S3"
add_alias "product" "Amazon EC2" "EC2"
add_alias "product" "Amazon RDS" "RDS"
add_alias "product" "Amazon Lambda" "Lambda"
add_alias "product" "Amazon SageMaker" "SageMaker"

# Tesla Products
add_alias "product" "Tesla Model 3" "Model 3"
add_alias "product" "Tesla Model Y" "Model Y"
add_alias "product" "Tesla Model S" "Model S"
add_alias "product" "Tesla Model X" "Model X"
add_alias "product" "Tesla Cybertruck" "Cybertruck"
add_alias "product" "Tesla Semi" "Tesla Semi Truck"
add_alias "product" "Tesla Roadster" "Roadster"
add_alias "product" "Powerwall" "Tesla Powerwall"
add_alias "product" "Powerpack" "Tesla Powerpack"
add_alias "product" "Megapack" "Tesla Megapack"
add_alias "product" "Solar Roof" "Tesla Solar Roof"
add_alias "product" "Tesla Solar Panels" "Solar Panels"
add_alias "product" "Tesla Supercharger" "Supercharger"
add_alias "product" "Tesla Autopilot" "Autopilot"
add_alias "product" "Full Self-Driving" "FSD"

# Sony Products
add_alias "product" "PlayStation" "Sony PlayStation"
add_alias "product" "PlayStation 5" "PS5"
add_alias "product" "PlayStation 4" "PS4"
add_alias "product" "PlayStation VR" "PSVR"
add_alias "product" "PlayStation Plus" "PS Plus"
add_alias "product" "PlayStation Network" "PSN"
add_alias "product" "Sony Bravia" "Bravia"
add_alias "product" "Sony Alpha" "α"
add_alias "product" "Sony WH-1000XM5" "WH-1000XM5"
add_alias "product" "Sony WF-1000XM5" "WF-1000XM5"
add_alias "product" "Sony Walkman" "Walkman"
add_alias "product" "PlayStation Portal" "PS Portal"

# Meta Products
add_alias "product" "Quest" "Meta Quest"
add_alias "product" "Quest 3" "Meta Quest 3"
add_alias "product" "Quest Pro" "Meta Quest Pro"
add_alias "product" "Ray-Ban Meta" "Ray-Ban Smart Glasses"
add_alias "product" "Instagram" "Meta Instagram"
add_alias "product" "WhatsApp" "Meta WhatsApp"
add_alias "product" "Messenger" "Facebook Messenger"
add_alias "product" "Horizon Worlds" "Meta Horizon Worlds"
add_alias "product" "Meta AI" "Meta's AI assistant"

# AI & Software Products
add_alias "product" "ChatGPT" "GPT-4"
add_alias "product" "ChatGPT" "OpenAI ChatGPT"
add_alias "product" "ChatGPT Plus" "ChatGPT+"
add_alias "product" "DALL-E" "DALL-E 3"
add_alias "product" "DALL-E" "OpenAI DALL-E"
add_alias "product" "Midjourney" "Midjourney AI"
add_alias "product" "Stable Diffusion" "Stability AI Stable Diffusion"
add_alias "product" "GitHub Copilot" "Copilot"
add_alias "product" "Claude" "Anthropic Claude"
add_alias "product" "Claude 2" "Anthropic Claude 2"
add_alias "product" "Claude Instant" "Anthropic Claude Instant"
add_alias "product" "Photoshop" "Adobe Photoshop"
add_alias "product" "Photoshop" "PS"
add_alias "product" "Lightroom" "Adobe Lightroom"
add_alias "product" "Illustrator" "Adobe Illustrator"
add_alias "product" "Premiere Pro" "Adobe Premiere"
add_alias "product" "After Effects" "Adobe After Effects"
add_alias "product" "InDesign" "Adobe InDesign"
add_alias "product" "Adobe Creative Cloud" "Creative Cloud"
add_alias "product" "Figma" "Adobe Figma"
add_alias "product" "Canva" "Canva Design"
add_alias "product" "Notion" "Notion App"
add_alias "product" "Slack" "Slack messenger"
add_alias "product" "Zoom" "Zoom Meetings"
add_alias "product" "Zoom" "Zoom Video"
add_alias "product" "Dropbox" "Dropbox Storage"
add_alias "product" "Salesforce" "Salesforce CRM"

# Gaming Products
add_alias "product" "PlayStation 5" "Sony PS5"
add_alias "product" "Nintendo Switch" "Switch"
add_alias "product" "Nintendo Switch OLED" "Switch OLED"
add_alias "product" "Nintendo Switch Lite" "Switch Lite"
add_alias "product" "Steam Deck" "Valve Steam Deck"
add_alias "product" "Oculus Quest" "Meta Quest"
add_alias "product" "Oculus Rift" "Meta Rift"
add_alias "product" "Call of Duty" "COD"
add_alias "product" "League of Legends" "LoL"
add_alias "product" "Fortnite" "Epic Games Fortnite"
add_alias "product" "Minecraft" "Microsoft Minecraft"
add_alias "product" "Roblox" "Roblox Platform"
add_alias "product" "Grand Theft Auto" "GTA"
add_alias "product" "The Legend of Zelda" "Zelda"
add_alias "product" "Final Fantasy" "FF"
add_alias "product" "Counter-Strike" "CS:GO"
add_alias "product" "Counter-Strike 2" "CS2"

# Automotive Products
add_alias "product" "Ford F-150" "F-150"
add_alias "product" "Ford F-150 Lightning" "F-150 Lightning"
add_alias "product" "Ford Mustang" "Mustang"
add_alias "product" "Ford Mustang Mach-E" "Mach-E"
add_alias "product" "Chevrolet Silverado" "Chevy Silverado"
add_alias "product" "Chevrolet Corvette" "Chevy Corvette"
add_alias "product" "Chevrolet Corvette" "Vette"
add_alias "product" "Toyota Camry" "Camry"
add_alias "product" "Toyota Corolla" "Corolla"
add_alias "product" "Toyota RAV4" "RAV4"
add_alias "product" "Toyota Prius" "Prius"
add_alias "product" "Honda Civic" "Civic"
add_alias "product" "Honda Accord" "Accord"
add_alias "product" "Honda CR-V" "CR-V"
add_alias "product" "BMW 3 Series" "3 Series"
add_alias "product" "BMW 5 Series" "5 Series"
add_alias "product" "BMW X5" "X5"
add_alias "product" "Mercedes-Benz C-Class" "C-Class"
add_alias "product"  "Mercedes-Benz E-Class" "E-Class"
add_alias "product" "Mercedes-Benz S-Class" "S-Class"
add_alias "product" "Audi A4" "A4"
add_alias "product" "Audi Q5" "Q5"
add_alias "product" "Jeep Wrangler" "Wrangler"
add_alias "product" "Jeep Grand Cherokee" "Grand Cherokee"
add_alias "product" "Porsche 911" "911"
add_alias "product" "Porsche Taycan" "Taycan"
add_alias "product" "Rivian R1T" "R1T"
add_alias "product" "Rivian R1S" "R1S"
add_alias "product" "Lucid Air" "Air"
add_alias "product" "Hyundai Ioniq 5" "Ioniq 5"
add_alias "product" "Kia EV6" "EV6"

# Home & Appliance Products
add_alias "product" "Dyson V15" "Dyson V15 Detect"
add_alias "product" "Dyson Airwrap" "Airwrap"
add_alias "product" "Dyson Air Purifier" "Dyson Purifier"
add_alias "product" "Roomba" "iRobot Roomba"
add_alias "product" "Instant Pot" "Instant Pot Pressure Cooker"
add_alias "product" "Ninja Foodi" "Foodi"
add_alias "product" "KitchenAid Stand Mixer" "KitchenAid Mixer"
add_alias "product" "KitchenAid Stand Mixer" "KitchenAid"
add_alias "product" "Nespresso" "Nespresso Machine"
add_alias "product" "Keurig" "Keurig Coffee Maker"
add_alias "product" "Sonos" "Sonos Speaker"
add_alias "product" "Sonos Arc" "Arc Soundbar"
add_alias "product" "Philips Hue" "Hue Lights"
add_alias "product" "Weber Grill" "Weber"
add_alias "product" "Traeger" "Traeger Grill"
add_alias "product" "Vitamix" "Vitamix Blender"
add_alias "product" "Peloton" "Peloton Bike"
add_alias "product" "Peloton Tread" "Peloton Treadmill"

# Wearable Technology
add_alias "product" "Fitbit" "Google Fitbit"
add_alias "product" "Fitbit Versa" "Versa"
add_alias "product" "Garmin" "Garmin Watch"
add_alias "product" "Garmin Fenix" "Fenix"
add_alias "product" "Oura Ring" "Oura"
add_alias "product" "Whoop" "Whoop Band"
add_alias "product" "Bose QuietComfort" "Bose QC"
add_alias "product" "Bose" "Bose Headphones"
add_alias "product" "Beats" "Apple Beats"
add_alias "product" "Beats Studio" "Studio Headphones"
add_alias "product" "Sennheiser" "Sennheiser Headphones"

# Financial & Business Products
add_alias "product" "Stripe" "Stripe Payments"
add_alias "product" "Square" "Block Square"
add_alias "product" "Square" "Square Terminal"
add_alias "product" "PayPal" "PayPal Payments"
add_alias "product" "Venmo" "Venmo App"
add_alias "product" "Cash App" "Square Cash App"
add_alias "product" "QuickBooks" "Intuit QuickBooks"
add_alias "product" "TurboTax" "Intuit TurboTax"
add_alias "product" "Shopify" "Shopify Platform"
add_alias "product" "Shopify POS" "Shopify Point of Sale"
add_alias "product" "HubSpot" "HubSpot CRM"
add_alias "product" "Asana" "Asana Project Management"
add_alias "product" "Trello" "Trello Boards"
add_alias "product" "Jira" "Atlassian Jira"
add_alias "product" "Confluence" "Atlassian Confluence"
add_alias "product" "Tableau" "Salesforce Tableau"
add_alias "product" "Tableau" "Tableau Software"
add_alias "product" "Oracle NetSuite" "NetSuite"
add_alias "product" "SAP" "SAP ERP"
add_alias "product" "Workday" "Workday HCM"

# Telecom Products
add_alias "product" "Verizon 5G" "Verizon 5G Network"
add_alias "product" "T-Mobile 5G" "T-Mobile 5G Network"
add_alias "product" "AT&T Fiber" "AT&T Fiber Internet"
add_alias "product" "Comcast Xfinity" "Xfinity"
add_alias "product" "Xfinity Internet" "Comcast Internet"
add_alias "product" "Spectrum" "Charter Spectrum"
add_alias "product" "Google Fi" "Fi Wireless"
add_alias "product" "Starlink" "SpaceX Starlink"

# Healthcare & Wellness Products
add_alias "product" "Apple Health" "Health app"
add_alias "product" "Pfizer vaccine" "Pfizer-BioNTech vaccine"
add_alias "product" "Pfizer vaccine" "Comirnaty"
add_alias "product" "Moderna vaccine" "Spikevax"
add_alias "product" "Johnson & Johnson vaccine" "J&J vaccine"
add_alias "product" "Johnson & Johnson vaccine" "Janssen vaccine"
add_alias "product" "Paxlovid" "Pfizer Paxlovid"
add_alias "product" "Ozempic" "Novo Nordisk Ozempic"
add_alias "product" "Wegovy" "Novo Nordisk Wegovy"
add_alias "product" "Lipitor" "Pfizer Lipitor"
add_alias "product" "Lipitor" "atorvastatin"
add_alias "product" "Advil" "ibuprofen"
add_alias "product" "Tylenol" "acetaminophen"
add_alias "product" "Tylenol" "paracetamol"
add_alias "product" "Theraflu" "GSK Theraflu"

# Energy & Industrial Products
add_alias "product" "Tesla Solar" "Tesla Solar Panels"
add_alias "product" "SolarCity" "Tesla SolarCity"
add_alias "product" "Nest Thermostat" "Google Nest Thermostat"
add_alias "product" "Ecobee" "Ecobee Thermostat"
add_alias "product" "GE Appliances" "General Electric Appliances"
add_alias "product" "Siemens" "Siemens Industrial"
add_alias "product" "Honeywell" "Honeywell system"
add_alias "product" "Caterpillar" "CAT equipment"
add_alias "product" "John Deere" "Deere equipment"

# Retail & E-commerce Products
add_alias "product" "Amazon Prime" "Prime membership"
add_alias "product" "Walmart+" "Walmart Plus"
add_alias "product" "Target Circle" "Circle rewards"
add_alias "product" "Costco Membership" "Costco Card"
add_alias "product" "Sam's Club" "Sam's Club Membership"

echo "==== ADDING LOCATION ALIASES ===="

# -------- COUNTRIES --------
# North America
add_alias "location" "United States" "USA"
add_alias "location" "United States" "US"
add_alias "location" "United States" "United States of America"
add_alias "location" "United States" "États-Unis"
add_alias "location" "United States" "Estados Unidos"
add_alias "location" "United States" "Vereinigte Staaten"
add_alias "location" "Canada" "Kanada"
add_alias "location" "Canada" "le Canada"
add_alias "location" "Mexico" "México"
add_alias "location" "Mexico" "Mexique"
add_alias "location" "Mexico" "Mexiko"

# South America
add_alias "location" "Brazil" "Brasil"
add_alias "location" "Brazil" "Brésil"
add_alias "location" "Brazil" "Brasilien"
add_alias "location" "Argentina" "Argentinien"
add_alias "location" "Argentina" "Argentine"
add_alias "location" "Colombia" "Kolumbien"
add_alias "location" "Colombia" "Colombie"
add_alias "location" "Chile" "Chili"
add_alias "location" "Peru" "Pérou"
add_alias "location" "Peru" "Perú"
add_alias "location" "Venezuela" "Vénézuéla"

# Western Europe
add_alias "location" "United Kingdom" "UK"
add_alias "location" "United Kingdom" "Great Britain"
add_alias "location" "United Kingdom" "Royaume-Uni"
add_alias "location" "United Kingdom" "Vereinigtes Königreich"
add_alias "location" "United Kingdom" "Reino Unido"
add_alias "location" "United Kingdom" "Großbritannien"
add_alias "location" "Ireland" "Éire"
add_alias "location" "Ireland" "Irland"
add_alias "location" "Ireland" "Irlande"
add_alias "location" "Ireland" "Irlanda"
add_alias "location" "France" "Frankreich"
add_alias "location" "France" "Francia"
add_alias "location" "France" "la France"
add_alias "location" "Germany" "Deutschland"
add_alias "location" "Germany" "Allemagne"
add_alias "location" "Germany" "Alemania"
add_alias "location" "Spain" "España"
add_alias "location" "Spain" "Espagne"
add_alias "location" "Spain" "Spanien"
add_alias "location" "Portugal" "República Portuguesa"
add_alias "location" "Portugal" "le Portugal"
add_alias "location" "Italy" "Italia"
add_alias "location" "Italy" "Italie"
add_alias "location" "Italy" "Italien"

# Northern Europe
add_alias "location" "Sweden" "Sverige"
add_alias "location" "Sweden" "Suède"
add_alias "location" "Sweden" "Schweden"
add_alias "location" "Sweden" "Suecia"
add_alias "location" "Norway" "Norge"
add_alias "location" "Norway" "Norvège"
add_alias "location" "Norway" "Norwegen"
add_alias "location" "Norway" "Noruega"
add_alias "location" "Denmark" "Danmark"
add_alias "location" "Denmark" "Danemark"
add_alias "location" "Denmark" "Dänemark"
add_alias "location" "Denmark" "Dinamarca"
add_alias "location" "Finland" "Suomi"
add_alias "location" "Finland" "Finlande"
add_alias "location" "Finland" "Finnland"
add_alias "location" "Finland" "Finlandia"
add_alias "location" "Iceland" "Ísland"
add_alias "location" "Iceland" "Islande"
add_alias "location" "Iceland" "Island"
add_alias "location" "Iceland" "Islandia"

# Central & Eastern Europe
add_alias "location" "Poland" "Polska"
add_alias "location" "Poland" "Pologne"
add_alias "location" "Poland" "Polen"
add_alias "location" "Poland" "Polonia"
add_alias "location" "Czech Republic" "Česko"
add_alias "location" "Czech Republic" "Czechia"
add_alias "location" "Czech Republic" "République tchèque"
add_alias "location" "Czech Republic" "Tschechien"
add_alias "location" "Czech Republic" "República Checa"
add_alias "location" "Slovakia" "Slovensko"
add_alias "location" "Slovakia" "Slovaquie"
add_alias "location" "Slovakia" "Slowakei"
add_alias "location" "Slovakia" "Eslovaquia"
add_alias "location" "Hungary" "Magyarország"
add_alias "location" "Hungary" "Hongrie"
add_alias "location" "Hungary" "Ungarn"
add_alias "location" "Hungary" "Hungría"
add_alias "location" "Romania" "România"
add_alias "location" "Romania" "Roumanie"
add_alias "location" "Romania" "Rumänien"
add_alias "location" "Romania" "Rumania"
add_alias "location" "Bulgaria" "България"
add_alias "location" "Bulgaria" "Bulgarie"
add_alias "location" "Bulgaria" "Bulgarien"

# Baltic States
add_alias "location" "Estonia" "Eesti"
add_alias "location" "Estonia" "Estonie"
add_alias "location" "Estonia" "Estland"
add_alias "location" "Estonia" "Estonia"
add_alias "location" "Latvia" "Latvija"
add_alias "location" "Latvia" "Lettonie"
add_alias "location" "Latvia" "Lettland"
add_alias "location" "Latvia" "Letonia"
add_alias "location" "Lithuania" "Lietuva"
add_alias "location" "Lithuania" "Lituanie"
add_alias "location" "Lithuania" "Litauen"
add_alias "location" "Lithuania" "Lituania"

# Balkans
add_alias "location" "Croatia" "Hrvatska"
add_alias "location" "Croatia" "Croatie"
add_alias "location" "Croatia" "Kroatien"
add_alias "location" "Croatia" "Croacia"
add_alias "location" "Serbia" "Србија"
add_alias "location" "Serbia" "Serbie"
add_alias "location" "Serbia" "Serbien"
add_alias "location" "Montenegro" "Црна Гора"
add_alias "location" "Montenegro" "Monténégro"
add_alias "location" "Montenegro" "Montenegro"
add_alias "location" "North Macedonia" "Северна Македонија"
add_alias "location" "North Macedonia" "Macédoine du Nord"
add_alias "location" "North Macedonia" "Nordmazedonien"
add_alias "location" "North Macedonia" "Macedonia del Norte"
add_alias "location" "Slovenia" "Slovenija"
add_alias "location" "Slovenia" "Slovénie"
add_alias "location" "Slovenia" "Slowenien"
add_alias "location" "Slovenia" "Eslovenia"
add_alias "location" "Bosnia and Herzegovina" "Bosna i Hercegovina"
add_alias "location" "Bosnia and Herzegovina" "Bosnie-Herzégovine"
add_alias "location" "Bosnia and Herzegovina" "Bosnien und Herzegowina"
add_alias "location" "Bosnia and Herzegovina" "Bosnia y Herzegovina"
add_alias "location" "Albania" "Shqipëria"
add_alias "location" "Albania" "Albanie"
add_alias "location" "Albania"  "Albanien"

# Benelux
add_alias "location" "Netherlands" "Nederland"
add_alias "location" "Netherlands" "Pays-Bas"
add_alias "location" "Netherlands" "Niederlande"
add_alias "location" "Netherlands" "Países Bajos"
add_alias "location" "Netherlands" "Holland"
add_alias "location" "Belgium" "België"
add_alias "location" "Belgium" "Belgique"
add_alias "location" "Belgium" "Belgien"
add_alias "location" "Belgium" "Bélgica"
add_alias "location" "Luxembourg" "Luxemburg"
add_alias "location" "Luxembourg" "Lëtzebuerg"

# Mediterranean
add_alias "location" "Greece" "Ελλάδα"
add_alias "location" "Greece" "Grèce"
add_alias "location" "Greece" "Griechenland"
add_alias "location" "Greece" "Grecia"
add_alias "location" "Malta" "Malte"
add_alias "location" "Cyprus" "Κύπρος"
add_alias "location" "Cyprus" "Kibris"
add_alias "location" "Cyprus" "Chypre"
add_alias "location" "Cyprus" "Zypern"
add_alias "location" "Cyprus" "Chipre"

# Asia - East & South East
add_alias "location" "China" "中国"
add_alias "location" "China" "Zhōngguó"
add_alias "location" "China" "People's Republic of China"
add_alias "location" "China" "Chine"
add_alias "location" "China" "China"
add_alias "location" "Japan" "日本"
add_alias "location" "Japan" "Nihon"
add_alias "location" "Japan" "Japon"
add_alias "location" "Japan" "Japón"
add_alias "location" "Japan" "Japan"
add_alias "location" "South Korea" "대한민국"
add_alias "location" "South Korea" "Republic of Korea"
add_alias "location" "South Korea" "Corée du Sud"
add_alias "location" "South Korea" "Südkorea"
add_alias "location" "South Korea" "Corea del Sur"
add_alias "location" "North Korea" "조선민주주의인민공화국"
add_alias "location" "North Korea" "Democratic People's Republic of Korea"
add_alias "location" "North Korea" "Corée du Nord"
add_alias "location" "North Korea" "Nordkorea"
add_alias "location" "North Korea" "Corea del Norte"
add_alias "location" "Taiwan" "臺灣"
add_alias "location" "Taiwan" "Republic of China"
add_alias "location" "Taiwan" "Taïwan"
add_alias "location" "Taiwan" "Taiwán"
add_alias "location" "Vietnam" "Việt Nam"
add_alias "location" "Vietnam" "Viêt Nam"
add_alias "location" "Thailand" "ประเทศไทย"
add_alias "location" "Thailand" "Prathet Thai"
add_alias "location" "Thailand" "Thaïlande"
add_alias "location" "Thailand" "Tailandia"
add_alias "location" "Thailand" "Thailand"
add_alias "location" "Indonesia" "Indonesia"
add_alias "location" "Indonesia" "Indonésie"
add_alias "location" "Indonesia" "Indonesien"
add_alias "location" "Malaysia" "Malaisie"
add_alias "location" "Malaysia" "Malasia"
add_alias "location" "Singapore" "新加坡"
add_alias "location" "Singapore" "Singapour"
add_alias "location" "Singapore" "Singapur"
add_alias "location" "Philippines" "Pilipinas"
add_alias "location" "Philippines" "Filipinas"

# Asia - South & Central
add_alias "location" "India" "भारत"
add_alias "location" "India" "Bhārat"
add_alias "location" "India" "Inde"
add_alias "location" "India" "Indien"
add_alias "location" "Pakistan" "پاکستان"
add_alias "location" "Pakistan" "Pakistán"
add_alias "location" "Bangladesh" "বাংলাদেশ"
add_alias "location" "Sri Lanka" "ශ්‍රී ලංකාව"
add_alias "location" "Sri Lanka" "இலங்கை"
add_alias "location" "Nepal" "नेपाल"
add_alias "location" "Nepal" "Népal"
add_alias "location" "Kazakhstan" "Қазақстан"
add_alias "location" "Kazakhstan" "Kasachstan"
add_alias "location" "Kazakhstan" "Kazajistán"
add_alias "location" "Uzbekistan" "Oʻzbekiston"
add_alias "location" "Uzbekistan" "Ouzbékistan"
add_alias "location" "Uzbekistan" "Usbekistan"

# Middle East
add_alias "location" "Turkey" "Türkiye"
add_alias "location" "Turkey" "Turquie"
add_alias "location" "Turkey" "Türkei"
add_alias "location" "Turkey" "Turquía"
add_alias "location" "Iran" "ایران"
add_alias "location" "Iran" "République islamique d'Iran"
add_alias "location" "Saudi Arabia" "المملكة العربية السعودية"
add_alias "location" "Saudi Arabia" "Kingdom of Saudi Arabia"
add_alias "location" "Saudi Arabia" "Arabie saoudite"
add_alias "location" "Saudi Arabia" "Saudi-Arabien"
add_alias "location" "Saudi Arabia" "Arabia Saudita"
add_alias "location" "Israel" "ישראל"
add_alias "location" "Israel" "إسرائيل"
add_alias "location" "Israel" "Israël"
add_alias "location" "United Arab Emirates" "UAE"
add_alias "location" "United Arab Emirates" "الإمارات العربية المتحدة"
add_alias "location" "United Arab Emirates" "Emirats arabes unis"
add_alias "location" "United Arab Emirates" "Vereinigte Arabische Emirate"
add_alias "location" "United Arab Emirates" "Emiratos Árabes Unidos"
add_alias "location" "Qatar" "قطر"
add_alias "location" "Qatar" "Katar"
add_alias "location" "Iraq" "العراق"
add_alias "location" "Iraq" "Irak"

# Africa
add_alias "location" "Egypt" "مصر"
add_alias "location" "Egypt" "Misr"
add_alias "location" "Egypt" "Égypte"
add_alias "location" "Egypt" "Ägypten"
add_alias "location" "Egypt" "Egipto"
add_alias "location" "South Africa" "Suid-Afrika"
add_alias "location" "South Africa" "Afrique du Sud"
add_alias "location" "South Africa" "Südafrika"
add_alias "location" "South Africa" "Sudáfrica"
add_alias "location" "Nigeria" "Nigéria"
add_alias "location" "Nigeria" "Nigèria"
add_alias "location" "Kenya" "Kenia"
add_alias "location" "Morocco" "المغرب"
add_alias "location" "Morocco" "Maroc"
add_alias "location" "Morocco" "Marokko"
add_alias "location" "Morocco" "Marruecos"
add_alias "location" "Algeria" "الجزائر"
add_alias "location" "Algeria" "Algérie"
add_alias "location" "Algeria" "Al-Dschazāʾir"
add_alias "location" "Ethiopia" "ኢትዮጵያ"
add_alias "location" "Ethiopia" "Éthiopie"
add_alias "location" "Ethiopia" "Äthiopien"
add_alias "location" "Ethiopia" "Etiopía"
add_alias "location" "Ghana" "Gana"

# Oceania
add_alias "location" "Australia" "Australie"
add_alias "location" "Australia" "Australien"
add_alias "location" "New Zealand" "Aotearoa"
add_alias "location" "New Zealand" "Nouvelle-Zélande"
add_alias "location" "New Zealand" "Neuseeland"
add_alias "location" "New Zealand" "Nueva Zelanda"

# Eastern Europe & Russia
add_alias "location" "Russia" "Россия"
add_alias "location" "Russia" "Rossiya"
add_alias "location" "Russia" "Russian Federation"
add_alias "location" "Russia" "Russie"
add_alias "location" "Russia" "Russland"
add_alias "location" "Russia" "Rusia"
add_alias "location" "Ukraine" "Україна"
add_alias "location" "Ukraine" "Ukraina"
add_alias "location" "Ukraine" "Ucrania"
add_alias "location" "Ukraine" "Ucrania"
add_alias "location" "Belarus" "Беларусь"
add_alias "location" "Belarus" "Biélorussie"
add_alias "location" "Belarus" "Weißrussland"
add_alias "location" "Belarus" "Bielorrusia"
add_alias "location" "Moldova" "Молдова"
add_alias "location" "Moldova" "Moldavie"
add_alias "location" "Moldova" "Moldawien"
add_alias "location" "Moldova" "Moldavia"

# -------- MAJOR WORLD CITIES --------
# North American Cities
add_alias "location" "New York City" "NYC"
add_alias "location" "New York City" "New York"
add_alias "location" "New York City" "Nueva York"
add_alias "location" "New York City" "Nova Iorque"
add_alias "location" "New York City" "Нью-Йорк"
add_alias "location" "Los Angeles" "LA"
add_alias "location" "Los Angeles" "Los Ángeles"
add_alias "location" "Los Angeles" "Los Angeles"
add_alias "location" "Chicago" "Чикаго"
add_alias "location" "Chicago" "Şikago"
add_alias "location" "San Francisco" "SF"
add_alias "location" "San Francisco" "San Fran"
add_alias "location" "San Francisco" "Сан-Франциско"
add_alias "location" "Washington DC" "Washington"
add_alias "location" "Washington DC" "DC"
add_alias "location" "Washington DC" "Washington D.C."
add_alias "location" "Washington DC" "District of Columbia"
add_alias "location" "Washington DC" "Вашингтон"
add_alias "location" "Toronto" "Торонто"
add_alias "location" "Toronto" "Торонто"
add_alias "location" "Mexico City" "Ciudad de México"
add_alias "location" "Mexico City" "CDMX"
add_alias "location" "Mexico City" "Mexico DF"
add_alias "location" "Mexico City" "Ciudad de México"
add_alias "location" "Mexico City" "Ville de Mexico"

# European Cities
add_alias "location" "London" "Londres"
add_alias "location" "London" "Londra"
add_alias "location" "London" "Лондон"
add_alias "location" "London" "London, UK"
add_alias "location" "London" "London, England"
add_alias "location" "Paris" "Париж"
add_alias "location" "Paris" "Parigi"
add_alias "location" "Paris" "Parijs"
add_alias "location" "Paris" "Paris, France"
add_alias "location" "Berlin" "Берлин"
add_alias "location" "Berlin" "Berlín"
add_alias "location" "Berlin" "Berlino"
add_alias "location" "Berlin" "Berlin, Germany"
add_alias "location" "Madrid" "Мадрид"
add_alias "location" "Madrid" "Madri"
add_alias "location" "Madrid" "Madryt"
add_alias "location" "Madrid" "Madrid, Spain"
add_alias "location" "Rome" "Roma"
add_alias "location" "Rome" "Rom"
add_alias "location" "Rome" "Рим"
add_alias "location" "Rome" "Rome, Italy"
add_alias "location" "Amsterdam" "Амстердам"
add_alias "location" "Amsterdam" "Amsterdã"
add_alias "location" "Amsterdam" "Amsterdam, Netherlands"
add_alias "location" "Brussels" "Brüssel"
add_alias "location" "Brussels" "Bruxelles"
add_alias "location" "Brussels" "Brussel"
add_alias "location" "Brussels" "Bruselas"
add_alias "location" "Brussels" "Bryssel"
add_alias "location" "Brussels" "Brussels, Belgium"
add_alias "location" "Vienna" "Wien"
add_alias "location" "Vienna" "Вена"
add_alias "location" "Vienna" "Viena"
add_alias "location" "Vienna" "Viena"
add_alias "location" "Vienna" "Bécs"
add_alias "location" "Prague" "Praha"
add_alias "location" "Prague" "Прага"
add_alias "location" "Prague" "Prag"
add_alias "location" "Prague" "Praga"
add_alias "location" "Prague" "Prague, Czech Republic"
add_alias "location" "Stockholm" "Стокгольм"
add_alias "location" "Stockholm" "Stoccolma"
add_alias "location" "Stockholm" "Estocolmo"
add_alias "location" "Stockholm" "Stockholm, Sweden"
add_alias "location" "Budapest" "Будапешт"
add_alias "location" "Budapest" "Boedapest"
add_alias "location" "Budapest" "Budapest, Hungary"
add_alias "location" "Warsaw" "Warszawa"
add_alias "location" "Warsaw" "Варшава"
add_alias "location" "Warsaw" "Varsavia"
add_alias "location" "Warsaw" "Varsovia"
add_alias "location" "Warsaw" "Warsaw, Poland"
add_alias "location" "Athens" "Αθήνα"
add_alias "location" "Athens" "Atenas"
add_alias "location" "Athens" "Athènes"
add_alias "location" "Athens" "Athen"
add_alias "location" "Athens" "Athens, Greece"
add_alias "location" "Dublin" "Дублин"
add_alias "location" "Dublin" "Dublino"
add_alias "location" "Dublin" "Dublín"
add_alias "location" "Dublin" "Dublin, Ireland"

# Asian Cities
add_alias "location" "Tokyo" "東京"
add_alias "location" "Tokyo" "Tōkyō"
add_alias "location" "Tokyo" "Токио"
add_alias "location" "Tokyo" "Tokio"
add_alias "location" "Tokyo" "Tóquio"
add_alias "location" "Tokyo" "Tokyo, Japan"
add_alias "location" "Beijing" "北京"
add_alias "location" "Beijing" "Běijīng"
add_alias "location" "Beijing" "Пекин"
add_alias "location" "Beijing" "Pekín"
add_alias "location" "Beijing" "Pékin"
add_alias "location" "Beijing" "Beijing, China"
add_alias "location" "Shanghai" "上海"
add_alias "location" "Shanghai" "Шанхай"
add_alias "location" "Shanghai" "Shangai"
add_alias "location" "Shanghai" "Shanghai, China"
add_alias "location" "Hong Kong" "香港"
add_alias "location" "Hong Kong" "Xianggang"
add_alias "location" "Hong Kong" "Hongkong"
add_alias "location" "Hong Kong" "Hong Kong SAR"
add_alias "location" "Hong Kong" "Hong Kong, China"
add_alias "location" "Singapore" "新加坡"
add_alias "location" "Singapore" "Singapur"
add_alias "location" "Singapore" "Singapour"
add_alias "location" "Singapore" "Сингапур"
add_alias "location" "Seoul" "서울"
add_alias "location" "Seoul" "Сеул"
add_alias "location" "Seoul" "Seúl"
add_alias "location" "Seoul" "Séoul"
add_alias "location" "Seoul" "Seoul, South Korea"
add_alias "location" "Mumbai" "मुंबई"
add_alias "location" "Mumbai" "Bombay"
add_alias "location" "Mumbai" "Бомбей"
add_alias "location" "Mumbai" "Mumbai, India"
add_alias "location" "Bangkok" "กรุงเทพมหานคร"
add_alias "location" "Bangkok" "Krung Thep"
add_alias "location" "Bangkok" "Бангкок"
add_alias "location" "Bangkok" "Bangkok, Thailand"
add_alias "location" "Dubai" "دبي"
add_alias "location" "Dubai" "Дубай"
add_alias "location" "Dubai" "Dubai, UAE"
add_alias "location" "Istanbul" "İstanbul"
add_alias "location" "Istanbul" "Стамбул"
add_alias "location" "Istanbul" "Constantinopla"
add_alias "location" "Istanbul" "Constantinople"
add_alias "location" "Istanbul" "Istanbul, Turkey"

# Middle East Cities
add_alias "location" "Jerusalem" "ירושלים"
add_alias "location" "Jerusalem" "Al-Quds"
add_alias "location" "Jerusalem" "القدس‎"
add_alias "location" "Jerusalem" "Иерусалим"
add_alias "location" "Jerusalem" "Jerusalén"
add_alias "location" "Jerusalem" "Jérusalem"
add_alias "location" "Cairo" "القاهرة"
add_alias "location" "Cairo" "Al-Qāhira"
add_alias "location" "Cairo" "Каир"
add_alias "location" "Cairo" "Le Caire"
add_alias "location" "Cairo" "El Cairo"
add_alias "location" "Cairo" "Cairo, Egypt"
add_alias "location" "Riyadh" "الرياض"
add_alias "location" "Riyadh" "Ar-Riyād"
add_alias "location" "Riyadh" "Эр-Рияд"
add_alias "location" "Riyadh" "Riad"

# African Cities
add_alias "location" "Lagos" "Лагос"
add_alias "location" "Lagos" "Lagos, Nigeria"
add_alias "location" "Johannesburg" "Joburg"
add_alias "location" "Johannesburg" "Йоханнесбург"
add_alias "location" "Johannesburg" "Johannesburg, South Africa"
add_alias "location" "Cape Town" "Kaapstad"
add_alias "location" "Cape Town" "Кейптаун"
add_alias "location" "Cape Town" "Le Cap"
add_alias "location" "Cape Town" "Ciudad del Cabo"
add_alias "location" "Cape Town" "Kapstadt"
add_alias "location" "Nairobi" "Найроби"
add_alias "location" "Nairobi" "Nairobi, Kenya"
add_alias "location" "Casablanca" "الدار البيضاء"
add_alias "location" "Casablanca" "Касабланка"
add_alias "location" "Casablanca" "Casablanca, Morocco"

# South American Cities
add_alias "location" "São Paulo" "Sao Paulo"
add_alias "location" "São Paulo" "Сан-Паулу"
add_alias "location" "São Paulo" "São Paulo, Brazil"
add_alias "location" "Rio de Janeiro" "Рио-де-Жанейро"
add_alias "location" "Rio de Janeiro" "Rio"
add_alias "location" "Rio de Janeiro" "Rio de Janeiro, Brazil"
add_alias "location" "Buenos Aires" "Буэнос-Айрес"
add_alias "location" "Buenos Aires" "Buenos Aires, Argentina"
add_alias "location" "Lima" "Лима"
add_alias "location" "Lima" "Lima, Peru"
add_alias "location" "Bogotá" "Bogota"
add_alias "location" "Bogotá" "Богота"
add_alias "location" "Bogotá" "Bogotá, Colombia"

# Oceania Cities
add_alias "location" "Sydney" "Сидней"
add_alias "location" "Sydney" "Sídney"
add_alias "location" "Sydney" "Sidney"
add_alias "location" "Sydney" "Sydney, Australia"
add_alias "location" "Melbourne" "Мельбурн"
add_alias "location" "Melbourne" "Melbourne, Australia"
add_alias "location" "Auckland" "Окленд"
add_alias "location" "Auckland" "Auckland, New Zealand"

# -------- US STATES --------
add_alias "location" "California" "CA"
add_alias "location" "California" "Californie"
add_alias "location" "California" "Kalifornien"
add_alias "location" "California" "Калифорния"
add_alias "location" "Texas" "TX"
add_alias "location" "Texas" "Техас"
add_alias "location" "Florida" "FL"
add_alias "location" "Florida" "Floride"
add_alias "location" "Florida" "Флорида"
add_alias "location" "New York State" "New York"
add_alias "location" "New York State" "NY"
add_alias "location" "New York State" "Estado de Nueva York"
add_alias "location" "New York State" "État de New York"
add_alias "location" "New York State" "Нью-Йорк"
add_alias "location" "Massachusetts" "MA"
add_alias "location" "Massachusetts" "Mass"
add_alias "location" "Massachusetts" "Массачусетс"
add_alias "location" "Pennsylvania" "PA"
add_alias "location" "Pennsylvania" "Penn"
add_alias "location" "Pennsylvania" "Пенсильвания"
add_alias "location" "Illinois" "IL"
add_alias "location" "Illinois" "Иллинойс"
add_alias "location" "Washington State" "WA"
add_alias "location" "Washington State" "État de Washington"
add_alias "location" "Washington State" "Estado de Washington"
add_alias "location" "Washington State" "Вашингтон"
add_alias "location" "Arizona" "AZ"
add_alias "location" "Arizona" "Аризона"
add_alias "location" "Georgia" "GA"
add_alias "location" "Georgia" "Джорджия"
add_alias "location" "Georgia" "Géorgie"
add_alias "location" "Michigan" "MI"
add_alias "location" "Michigan" "Мичиган"
add_alias "location" "Ohio" "OH"
add_alias "location" "Ohio" "Огайо"
add_alias "location" "North Carolina" "NC"
add_alias "location" "North Carolina" "Caroline du Nord"
add_alias "location" "North Carolina" "Северная Каролина"
add_alias "location" "New Jersey" "NJ"
add_alias "location" "New Jersey" "Нью-Джерси"
add_alias "location" "Virginia" "VA"
add_alias "location" "Virginia" "Вирджиния"
add_alias "location" "Colorado" "CO"
add_alias "location" "Colorado" "Колорадо"
add_alias "location" "Minnesota" "MN"
add_alias "location" "Minnesota" "Миннесота"
add_alias "location" "Tennessee" "TN"
add_alias "location" "Tennessee" "Теннесси"
add_alias "location" "Wisconsin" "WI"
add_alias "location" "Wisconsin" "Висконсин"
add_alias "location" "Maryland" "MD"
add_alias "location" "Maryland" "Мэриленд"
add_alias "location" "South Carolina" "SC"
add_alias "location" "South Carolina" "Caroline du Sud"
add_alias "location" "South Carolina" "Южная Каролина"
add_alias "location" "Missouri" "MO"
add_alias "location" "Missouri" "Миссури"
add_alias "location" "Indiana" "IN"
add_alias "location" "Indiana" "Индиана"

# -------- PROVINCES & REGIONS --------
# Canadian Provinces
add_alias "location" "Ontario" "Онтарио"
add_alias "location" "Quebec" "Québec"
add_alias "location" "Quebec" "Квебек"
add_alias "location" "British Columbia" "BC"
add_alias "location" "British Columbia" "Colombie-Britannique"
add_alias "location" "British Columbia" "Британская Колумбия"
add_alias "location" "Alberta" "Альберта"

# Chinese Provinces
add_alias "location" "Guangdong" "广东"
add_alias "location" "Guangdong" "Guangdong Province"
add_alias "location" "Guangdong" "Canton"
add_alias "location" "Sichuan" "四川"
add_alias "location" "Sichuan" "Sichuan Province"
add_alias "location" "Jiangsu" "江苏"
add_alias "location" "Jiangsu" "Jiangsu Province"
add_alias "location" "Shandong" "山东"
add_alias "location" "Shandong" "Shandong Province"

# European Regions
add_alias "location" "Bavaria" "Bayern"
add_alias "location" "Bavaria" "Baviera"
add_alias "location" "Bavaria" "Бавария"
add_alias "location" "Bavaria" "Bavière"
add_alias "location" "Catalonia" "Catalunya"
add_alias "location" "Catalonia" "Cataluña"
add_alias "location" "Catalonia" "Catalogne"
add_alias "location" "Catalonia" "Katalonien"
add_alias "location" "Catalonia" "Каталония"
add_alias "location" "Tuscany" "Toscana"
add_alias "location" "Tuscany" "Toscane"
add_alias "location" "Tuscany" "Тоскана"
add_alias "location" "Normandy" "Normandie"
add_alias "location" "Normandy" "Normandia"
add_alias "location" "Normandy" "Normandië"
add_alias "location" "Normandy" "Нормандия"
add_alias "location" "Scotland" "Schottland"
add_alias "location" "Scotland" "Écosse"
add_alias "location" "Scotland" "Escocia"
add_alias "location" "Scotland" "Scozia"
add_alias "location" "Scotland" "Шотландия"

# Other Notable Areas
add_alias "location" "Silicon Valley" "Silicon Valley, California"
add_alias "location" "Silicon Valley" "Кремниевая долина"
add_alias "location" "Silicon Valley" "Valle del Silicio"
add_alias "location" "Silicon Valley" "Vallée du Silicium"
add_alias "location" "Siberia" "Сибирь"
add_alias "location" "Siberia" "Sibérie"
add_alias "location" "Siberia" "Sibirien"
add_alias "location" "Siberia" "Siberia"
add_alias "location" "Amazon Rainforest" "Amazon"
add_alias "location" "Amazon Rainforest" "Amazonia"
add_alias "location" "Amazon Rainforest" "Amazonie"
add_alias "location" "Amazon Rainforest" "Amazonas"
add_alias "location" "Amazon Rainforest" "Амазонские джунгли"

echo "Completed adding aliases for all entity types"
