#!/bin/bash
# This script adds common organization name patterns to the database
# Includes Fortune 500 and Fortune Global 500 companies
# Exit on error
set -e

# Function to add alias pair
add_alias() {
    echo "Adding alias: $1 ↔ $2"
    cargo run --bin manage_aliases -- add --canonical "$1" --alias "$2" --entity-type "organization" --source "pattern" --confidence 0.95
}

# First let's add the specific examples from tests
add_alias "Apple" "Apple Inc"
add_alias "Microsoft" "Microsoft Corporation" 
add_alias "Nike" "Nike, Inc"

# Common company suffix pairs
add_alias "Company" "Co"
add_alias "Corporation" "Corp"
add_alias "Incorporated" "Inc"
add_alias "Limited" "Ltd"
add_alias "Limited Liability Company" "LLC"
add_alias "Group" "Grp"
add_alias "Holdings" "Hldgs"
add_alias "International" "Intl"
add_alias "Enterprises" "Ent"
add_alias "Technologies" "Tech"
add_alias "Industries" "Ind"
add_alias "Partners" "Ptnrs"
add_alias "Solutions" "Solns"
add_alias "Manufacturing" "Mfg"
add_alias "Services" "Svcs"
add_alias "Systems" "Sys"
add_alias "Products" "Prods"
add_alias "Associates" "Assoc"

# -------- TECHNOLOGY COMPANIES --------
add_alias "Apple" "Apple Inc"
add_alias "Microsoft" "Microsoft Corporation"
add_alias "Alphabet" "Google"
add_alias "Alphabet" "Google LLC"
add_alias "Alphabet" "Alphabet Inc"
add_alias "Amazon" "Amazon.com Inc"
add_alias "Amazon" "Amazon.com"
add_alias "Amazon" "AMZN"
add_alias "Meta" "Meta Platforms Inc"
add_alias "Meta" "Facebook Inc"
add_alias "Meta Platforms" "Facebook"
add_alias "Meta" "FB"
add_alias "IBM" "International Business Machines Corporation"
add_alias "International Business Machines" "IBM"
add_alias "Tesla" "Tesla Inc"
add_alias "Tesla" "TSLA"
add_alias "Intel" "Intel Corporation"
add_alias "Intel" "INTC"
add_alias "AMD" "Advanced Micro Devices Inc"
add_alias "Advanced Micro Devices" "AMD"
add_alias "Cisco" "Cisco Systems Inc"
add_alias "Cisco Systems" "Cisco"
add_alias "Cisco" "CSCO"
add_alias "Oracle" "Oracle Corporation"
add_alias "Oracle" "ORCL"
add_alias "Twitter" "X Corp"
add_alias "X" "Twitter"
add_alias "Dell" "Dell Technologies Inc"
add_alias "Dell Technologies" "Dell"
add_alias "Dell" "Dell EMC"
add_alias "HP" "Hewlett Packard Enterprise"
add_alias "HP" "HP Inc"
add_alias "Hewlett Packard" "HP"
add_alias "HPE" "Hewlett Packard Enterprise"
add_alias "NVIDIA" "NVIDIA Corporation"
add_alias "NVIDIA" "NVDA"
add_alias "Salesforce" "Salesforce.com Inc"
add_alias "Salesforce" "Salesforce.com"
add_alias "Salesforce" "CRM"
add_alias "Adobe" "Adobe Inc"
add_alias "Adobe" "ADBE"
add_alias "PayPal" "PayPal Holdings Inc"
add_alias "PayPal" "PYPL"
add_alias "Qualcomm" "Qualcomm Incorporated"
add_alias "Qualcomm" "QCOM"
add_alias "Texas Instruments" "Texas Instruments Incorporated"
add_alias "Texas Instruments" "TI"
add_alias "Texas Instruments" "TXN"
add_alias "SAP" "SAP SE"
add_alias "ServiceNow" "ServiceNow Inc"
add_alias "ServiceNow" "NOW"
add_alias "Intuit" "Intuit Inc"
add_alias "Intuit" "INTU"
add_alias "Activision Blizzard" "Activision Blizzard Inc"
add_alias "Electronic Arts" "Electronic Arts Inc"
add_alias "Electronic Arts" "EA"
add_alias "Cognizant" "Cognizant Technology Solutions"
add_alias "Cognizant" "CTSH"
add_alias "Autodesk" "Autodesk Inc"
add_alias "Autodesk" "ADSK"
add_alias "Micron Technology" "Micron"
add_alias "Micron" "MU"
add_alias "Western Digital" "Western Digital Corporation"
add_alias "Western Digital" "WDC"
add_alias "Seagate" "Seagate Technology"
add_alias "Seagate" "STX"
add_alias "Broadcom" "Broadcom Inc"
add_alias "Broadcom" "AVGO"
add_alias "Analog Devices" "Analog Devices Inc"
add_alias "Analog Devices" "ADI"
add_alias "Applied Materials" "Applied Materials Inc"
add_alias "Applied Materials" "AMAT"
add_alias "Lam Research" "Lam Research Corporation"
add_alias "Lam Research" "LRCX"
add_alias "Fiserv" "Fiserv Inc"
add_alias "Fiserv" "FISV"
add_alias "Fidelity National Information Services" "FIS"
add_alias "Global Payments" "Global Payments Inc"
add_alias "Global Payments" "GPN"
add_alias "Motorola Solutions" "Motorola Solutions Inc"
add_alias "Motorola Solutions" "MSI"
add_alias "Workday" "Workday Inc"
add_alias "Workday" "WDAY"
add_alias "VMware" "VMware Inc"
add_alias "VMware" "VMW"
add_alias "Akamai" "Akamai Technologies Inc"
add_alias "Akamai" "AKAM"
add_alias "Citrix Systems" "Citrix"
add_alias "Citrix" "CTXS"
add_alias "Juniper Networks" "Juniper Networks Inc"
add_alias "Juniper Networks" "JNPR"
add_alias "NetApp" "NetApp Inc"
add_alias "NetApp" "NTAP"
add_alias "Fortinet" "Fortinet Inc"
add_alias "Fortinet" "FTNT"
add_alias "Palo Alto Networks" "Palo Alto Networks Inc"
add_alias "Palo Alto Networks" "PANW"
add_alias "Crowdstrike" "Crowdstrike Holdings Inc"
add_alias "Crowdstrike" "CRWD"
add_alias "Zoom" "Zoom Video Communications Inc"
add_alias "Zoom" "ZM"
add_alias "DocuSign" "DocuSign Inc"
add_alias "DocuSign" "DOCU"
add_alias "Snowflake" "Snowflake Inc"
add_alias "Snowflake" "SNOW"
add_alias "Palantir" "Palantir Technologies Inc"
add_alias "Palantir" "PLTR"
add_alias "Twilio" "Twilio Inc"
add_alias "Twilio" "TWLO"
add_alias "Shopify" "Shopify Inc"
add_alias "Shopify" "SHOP"

# -------- RETAIL & CONSUMER GOODS --------
add_alias "Walmart" "Walmart Inc"
add_alias "Walmart" "WMT"
add_alias "Nike" "Nike, Inc"
add_alias "Nike" "NKE"
add_alias "Target" "Target Corporation"
add_alias "Target" "TGT"
add_alias "Home Depot" "The Home Depot Inc"
add_alias "Home Depot" "HD"
add_alias "Costco" "Costco Wholesale Corporation"
add_alias "Costco" "COST"
add_alias "Lowe's" "Lowe's Companies Inc"
add_alias "Lowe's" "LOW"
add_alias "Kroger" "The Kroger Co"
add_alias "Kroger" "KR"
add_alias "Procter & Gamble" "P&G"
add_alias "Procter & Gamble" "The Procter & Gamble Company"
add_alias "Procter & Gamble" "PG"
add_alias "PepsiCo" "PepsiCo Inc"
add_alias "PepsiCo" "PEP"
add_alias "Coca-Cola" "The Coca-Cola Company"
add_alias "Coca-Cola" "KO"
add_alias "Coca-Cola" "Coke"
add_alias "Starbucks" "Starbucks Corporation"
add_alias "Starbucks" "SBUX"
add_alias "McDonald's" "McDonald's Corporation"
add_alias "McDonald's" "MCD"
add_alias "Walgreens" "Walgreens Boots Alliance"
add_alias "Walgreens" "WBA"
add_alias "CVS" "CVS Health"
add_alias "CVS Health" "CVS Health Corporation"
add_alias "CVS" "CVS Pharmacy"
add_alias "CVS" "CVS"
add_alias "Best Buy" "Best Buy Co Inc"
add_alias "Best Buy" "BBY"
add_alias "TJX" "The TJX Companies Inc"
add_alias "TJX" "TJX"
add_alias "Dollar General" "Dollar General Corporation"
add_alias "Dollar General" "DG"
add_alias "Gap" "The Gap Inc"
add_alias "Gap" "GPS"
add_alias "Macy's" "Macy's Inc"
add_alias "Macy's" "M"
add_alias "Kohl's" "Kohl's Corporation"
add_alias "Kohl's" "KSS"
add_alias "Dollar Tree" "Dollar Tree Inc"
add_alias "Dollar Tree" "DLTR"
add_alias "Ross Stores" "Ross Stores Inc"
add_alias "Ross Stores" "ROST"
add_alias "Nordstrom" "Nordstrom Inc"
add_alias "Nordstrom" "JWN"
add_alias "Foot Locker" "Foot Locker Inc"
add_alias "Foot Locker" "FL"
add_alias "Tractor Supply Company" "Tractor Supply Co"
add_alias "Tractor Supply" "TSCO"
add_alias "Ulta Beauty" "Ulta Beauty Inc"
add_alias "Ulta Beauty" "ULTA"
add_alias "AutoZone" "AutoZone Inc"
add_alias "AutoZone" "AZO"
add_alias "O'Reilly Automotive" "O'Reilly Auto Parts"
add_alias "O'Reilly Automotive" "ORLY"
add_alias "Advance Auto Parts" "Advance Auto Parts Inc"
add_alias "Advance Auto Parts" "AAP"
add_alias "Genuine Parts Company" "GPC"
add_alias "Tiffany & Co" "Tiffany"
add_alias "Estée Lauder" "The Estée Lauder Companies"
add_alias "Estée Lauder" "EL"
add_alias "Colgate-Palmolive" "Colgate-Palmolive Company"
add_alias "Colgate-Palmolive" "CL"
add_alias "Kimberly-Clark" "Kimberly-Clark Corporation"
add_alias "Kimberly-Clark" "KMB"
add_alias "Clorox" "The Clorox Company"
add_alias "Clorox" "CLX"
add_alias "Campbell Soup" "Campbell Soup Company"
add_alias "Campbell Soup" "CPB"
add_alias "Kraft Heinz" "The Kraft Heinz Company"
add_alias "Kraft Heinz" "KHC"
add_alias "General Mills" "General Mills Inc"
add_alias "General Mills" "GIS"
add_alias "Kellogg" "Kellogg Company"
add_alias "Kellogg" "K"
add_alias "ConAgra" "ConAgra Brands Inc"
add_alias "ConAgra" "CAG"
add_alias "Mondelez" "Mondelez International"
add_alias "Mondelez" "MDLZ"
add_alias "Hershey" "The Hershey Company"
add_alias "Hershey" "HSY"
add_alias "J.M. Smucker" "The J.M. Smucker Company"
add_alias "J.M. Smucker" "SJM"

# -------- FINANCIAL SERVICES --------
add_alias "JPMorgan Chase" "JPMorgan Chase & Co"
add_alias "JPMorgan" "JPMorgan Chase"
add_alias "JPMorgan" "JPM"
add_alias "Bank of America" "Bank of America Corporation"
add_alias "Bank of America" "BofA"
add_alias "Bank of America" "BAC"
add_alias "Wells Fargo" "Wells Fargo & Company"
add_alias "Wells Fargo" "WFC"
add_alias "Citigroup" "Citigroup Inc"
add_alias "Citigroup" "Citi"
add_alias "Citigroup" "C"
add_alias "Goldman Sachs" "The Goldman Sachs Group Inc"
add_alias "Goldman Sachs" "GS"
add_alias "Morgan Stanley" "Morgan Stanley"
add_alias "Morgan Stanley" "MS"
add_alias "American Express" "American Express Company"
add_alias "American Express" "AmEx"
add_alias "American Express" "AXP"
add_alias "Visa" "Visa Inc"
add_alias "Visa" "V"
add_alias "Mastercard" "Mastercard Incorporated"
add_alias "Mastercard" "MA"
add_alias "BlackRock" "BlackRock Inc"
add_alias "BlackRock" "BLK"
add_alias "Capital One" "Capital One Financial Corporation"
add_alias "Capital One" "COF"
add_alias "U.S. Bancorp" "US Bancorp"
add_alias "U.S. Bancorp" "USB"
add_alias "Charles Schwab" "The Charles Schwab Corporation"
add_alias "Charles Schwab" "SCHW"
add_alias "State Street" "State Street Corporation"
add_alias "State Street" "STT"
add_alias "Travelers" "The Travelers Companies Inc"
add_alias "Travelers" "TRV"
add_alias "Prudential Financial" "Prudential Financial Inc"
add_alias "Prudential Financial" "PRU"
add_alias "MetLife" "MetLife Inc"
add_alias "MetLife" "MET"
add_alias "Allstate" "The Allstate Corporation"
add_alias "Allstate" "ALL"
add_alias "Progressive" "The Progressive Corporation"
add_alias "Progressive" "PGR"
add_alias "American International Group" "AIG"
add_alias "AIG" "American International Group Inc"
add_alias "Marsh & McLennan" "Marsh & McLennan Companies Inc"
add_alias "Marsh & McLennan" "MMC"
add_alias "Aon" "Aon plc"
add_alias "Aon" "AON"
add_alias "CME Group" "CME Group Inc"
add_alias "CME Group" "CME"
add_alias "Intercontinental Exchange" "ICE"
add_alias "Intercontinental Exchange" "Intercontinental Exchange Inc"
add_alias "S&P Global" "S&P Global Inc"
add_alias "S&P Global" "SPGI"
add_alias "Moody's" "Moody's Corporation"
add_alias "Moody's" "MCO"
add_alias "Synchrony Financial" "Synchrony"
add_alias "Synchrony Financial" "SYF"
add_alias "Discover Financial Services" "Discover"
add_alias "Discover Financial Services" "DFS"
add_alias "Northern Trust" "Northern Trust Corporation"
add_alias "Northern Trust" "NTRS"
add_alias "Bank of New York Mellon" "BNY Mellon"
add_alias "Bank of New York Mellon" "BK"
add_alias "Fifth Third Bancorp" "Fifth Third Bank"
add_alias "Fifth Third Bancorp" "FITB"
add_alias "PNC Financial Services" "PNC Bank"
add_alias "PNC Financial Services" "PNC"
add_alias "Truist Financial" "Truist Bank"
add_alias "Truist Financial" "TFC"
add_alias "M&T Bank" "M&T Bank Corporation"
add_alias "M&T Bank" "MTB"

# -------- HEALTHCARE --------
add_alias "UnitedHealth Group" "UnitedHealth Group Incorporated"
add_alias "UnitedHealth Group" "UNH"
add_alias "Johnson & Johnson" "Johnson & Johnson"
add_alias "J&J" "Johnson & Johnson"
add_alias "Johnson & Johnson" "JNJ"
add_alias "Pfizer" "Pfizer Inc"
add_alias "Pfizer" "PFE"
add_alias "Merck" "Merck & Co Inc"
add_alias "Merck" "MRK"
add_alias "AbbVie" "AbbVie Inc"
add_alias "AbbVie" "ABBV"
add_alias "Bristol Myers Squibb" "Bristol-Myers Squibb Company"
add_alias "Bristol Myers Squibb" "BMY"
add_alias "Eli Lilly" "Eli Lilly and Company"
add_alias "Eli Lilly" "LLY"
add_alias "Amgen" "Amgen Inc"
add_alias "Amgen" "AMGN"
add_alias "Abbott Laboratories" "Abbott"
add_alias "Abbott Laboratories" "ABT"
add_alias "Medtronic" "Medtronic plc"
add_alias "Medtronic" "MDT"
add_alias "Gilead Sciences" "Gilead Sciences Inc"
add_alias "Gilead Sciences" "GILD"
add_alias "Cigna" "Cigna Corporation"
add_alias "Cigna" "CI"
add_alias "Anthem" "Anthem Inc"
add_alias "Anthem" "Elevance Health"
add_alias "Anthem" "ANTM"
add_alias "Elevance Health" "ELV"
add_alias "Humana" "Humana Inc"
add_alias "Humana" "HUM"
add_alias "HCA Healthcare" "HCA Healthcare Inc"
add_alias "HCA Healthcare" "HCA"
add_alias "CVS Health" "CVS Health Corporation"
add_alias "CVS Health" "CVS"
add_alias "Centene" "Centene Corporation"
add_alias "Centene" "CNC"
add_alias "Regeneron Pharmaceuticals" "Regeneron"
add_alias "Regeneron Pharmaceuticals" "REGN"
add_alias "Biogen" "Biogen Inc"
add_alias "Biogen" "BIIB"
add_alias "Vertex Pharmaceuticals" "Vertex"
add_alias "Vertex Pharmaceuticals" "VRTX"
add_alias "Illumina" "Illumina Inc"
add_alias "Illumina" "ILMN"
add_alias "Baxter International" "Baxter"
add_alias "Baxter International" "BAX"
add_alias "Boston Scientific" "Boston Scientific Corporation"
add_alias "Boston Scientific" "BSX"
add_alias "Stryker" "Stryker Corporation"
add_alias "Stryker" "SYK"
add_alias "Becton, Dickinson" "BD"
add_alias "Becton, Dickinson" "Becton Dickinson"
add_alias "Becton, Dickinson" "BDX"
add_alias "Zimmer Biomet" "Zimmer Biomet Holdings Inc"
add_alias "Zimmer Biomet" "ZBH"
add_alias "Edwards Lifesciences" "Edwards Lifesciences Corporation"
add_alias "Edwards Lifesciences" "EW"
add_alias "Laboratory Corporation of America" "LabCorp"
add_alias "Laboratory Corporation of America" "LH"
add_alias "Quest Diagnostics" "Quest Diagnostics Incorporated"
add_alias "Quest Diagnostics" "DGX"
add_alias "DaVita" "DaVita Inc"
add_alias "DaVita" "DVA"
add_alias "McKesson" "McKesson Corporation"
add_alias "McKesson" "MCK"
add_alias "AmerisourceBergen" "AmerisourceBergen Corporation"
add_alias "AmerisourceBergen" "ABC"
add_alias "Cardinal Health" "Cardinal Health Inc"
add_alias "Cardinal Health" "CAH"
add_alias "Danaher" "Danaher Corporation"
add_alias "Danaher" "DHR"
add_alias "Thermo Fisher Scientific" "Thermo Fisher"
add_alias "Thermo Fisher Scientific" "TMO"
add_alias "Agilent Technologies" "Agilent"
add_alias "Agilent Technologies" "A"
add_alias "PerkinElmer" "PerkinElmer Inc"
add_alias "PerkinElmer" "PKI"
add_alias "Waters Corporation" "Waters"
add_alias "Waters Corporation" "WAT"
add_alias "IQVIA" "IQVIA Holdings Inc"
add_alias "IQVIA" "IQV"
add_alias "Universal Health Services" "UHS"

# -------- ENERGY & UTILITIES --------
add_alias "ExxonMobil" "Exxon Mobil Corporation"
add_alias "ExxonMobil" "XOM"
add_alias "Chevron" "Chevron Corporation"
add_alias "Chevron" "CVX"
add_alias "ConocoPhillips" "ConocoPhillips"
add_alias "ConocoPhillips" "COP"
add_alias "Marathon Petroleum" "Marathon Petroleum Corporation"
add_alias "Marathon Petroleum" "MPC"
add_alias "Phillips 66" "Phillips 66"
add_alias "Phillips 66" "PSX"
add_alias "Valero Energy" "Valero Energy Corporation"
add_alias "Valero Energy" "VLO"
add_alias "Duke Energy" "Duke Energy Corporation"
add_alias "Duke Energy" "DUK"
add_alias "Southern Company" "The Southern Company"
add_alias "Southern Company" "SO"
add_alias "NextEra Energy" "NextEra Energy Inc"
add_alias "NextEra Energy" "NEE"
add_alias "Dominion Energy" "Dominion Energy Inc"
add_alias "Dominion Energy" "D"
add_alias "Exelon" "Exelon Corporation"
add_alias "Exelon" "EXC"
add_alias "Occidental Petroleum" "Occidental Petroleum Corporation"
add_alias "Occidental Petroleum" "OXY"
add_alias "Baker Hughes" "Baker Hughes Company"
add_alias "Baker Hughes" "BKR"
add_alias "Halliburton" "Halliburton Company"
add_alias "Halliburton" "HAL"
add_alias "Schlumberger" "Schlumberger Limited"
add_alias "Schlumberger" "SLB"
add_alias "EOG Resources" "EOG Resources Inc"
add_alias "EOG Resources" "EOG"
add_alias "Pioneer Natural Resources" "Pioneer Natural Resources Company"
add_alias "Pioneer Natural Resources" "PXD"
add_alias "Kinder Morgan" "Kinder Morgan Inc"
add_alias "Kinder Morgan" "KMI"
add_alias "Williams Companies" "The Williams Companies Inc"
add_alias "Williams Companies" "WMB"
add_alias "ONEOK" "ONEOK Inc"
add_alias "ONEOK" "OKE"
add_alias "Devon Energy" "Devon Energy Corporation"
add_alias "Devon Energy" "DVN"
add_alias "Enbridge" "Enbridge Inc"
add_alias "Enbridge" "ENB"
add_alias "Enterprise Products Partners" "Enterprise Products"
add_alias "Enterprise Products Partners" "EPD"
add_alias "Consolidated Edison" "Con Edison"
add_alias "Consolidated Edison" "ED"
add_alias "American Electric Power" "American Electric Power Company"
add_alias "American Electric Power" "AEP"
add_alias "Sempra Energy" "Sempra"
add_alias "Sempra Energy" "SRE"
add_alias "Public Service Enterprise Group" "PSEG"
add_alias "Public Service Enterprise Group" "PEG"
add_alias "WEC Energy Group" "WEC Energy"
add_alias "WEC Energy Group" "WEC"
add_alias "Xcel Energy" "Xcel Energy Inc"
add_alias "Xcel Energy" "XEL"
add_alias "CenterPoint Energy" "CenterPoint Energy Inc"
add_alias "CenterPoint Energy" "CNP"
add_alias "DTE Energy" "DTE Energy Company"
add_alias "DTE Energy" "DTE"
add_alias "Entergy" "Entergy Corporation"
add_alias "Entergy" "ETR"
add_alias "FirstEnergy" "FirstEnergy Corp"
add_alias "FirstEnergy" "FE"
add_alias "PPL" "PPL Corporation"
add_alias "Edison International" "Edison International"
add_alias "Edison International" "EIX"
add_alias "Evergy" "Evergy Inc"
add_alias "Evergy" "EVRG"

# -------- AUTOMOTIVE --------
add_alias "General Motors" "General Motors Company"
add_alias "General Motors" "GM"
add_alias "Ford" "Ford Motor Company"
add_alias "Ford" "F"
add_alias "Toyota" "Toyota Motor Corporation"
add_alias "Toyota" "TM"
add_alias "Honda" "Honda Motor Co Ltd"
add_alias "Honda" "HMC"
add_alias "Stellantis" "Stellantis N.V."
add_alias "Stellantis" "STLA"
add_alias "Volkswagen" "Volkswagen AG"
add_alias "Volkswagen" "VWAGY"
add_alias "Volkswagen" "VW"
add_alias "BMW" "Bayerische Motoren Werke AG"
add_alias "BMW" "BMWYY"
add_alias "Daimler" "Daimler AG"
add_alias "Mercedes-Benz" "Mercedes-Benz Group AG"
add_alias "Mercedes-Benz" "MBGAF"
add_alias "Ferrari" "Ferrari N.V."
add_alias "Ferrari" "RACE"
add_alias "Porsche" "Porsche AG"
add_alias "Porsche" "POAHY"
add_alias "Nissan" "Nissan Motor Co Ltd"
add_alias "Nissan" "NSANY"
add_alias "Mazda" "Mazda Motor Corporation"
add_alias "Mazda" "MZDAY"
add_alias "Subaru" "Subaru Corporation"
add_alias "Subaru" "FUJHY"
add_alias "Kia" "Kia Corporation"
add_alias "Hyundai" "Hyundai Motor Company"
add_alias "Hyundai" "HYMTF"
add_alias "Renault" "Renault S.A."
add_alias "Renault" "RNLSY"
add_alias "Fiat Chrysler" "Fiat Chrysler Automobiles"
add_alias "BYD" "BYD Company"
add_alias "BYD" "BYDDY"
add_alias "Rivian" "Rivian Automotive Inc"
add_alias "Rivian" "RIVN"
add_alias "Lucid Group" "Lucid Motors"
add_alias "Lucid Group" "LCID"

# -------- TELECOMMUNICATIONS --------
add_alias "AT&T" "AT&T Inc"
add_alias "AT&T" "T"
add_alias "Verizon" "Verizon Communications Inc"
add_alias "Verizon" "VZ"
add_alias "Comcast" "Comcast Corporation"
add_alias "Comcast" "CMCSA"
add_alias "T-Mobile" "T-Mobile US Inc"
add_alias "T-Mobile" "TMUS"
add_alias "Charter Communications" "Charter Communications Inc"
add_alias "Charter Communications" "Spectrum"
add_alias "Charter Communications" "CHTR"
add_alias "Dish Network" "DISH Network Corporation"
add_alias "Dish Network" "DISH"
add_alias "Liberty Media" "Liberty Media Corporation"
add_alias "Liberty Media" "LSXMA"
add_alias "Deutsche Telekom" "Deutsche Telekom AG"
add_alias "Deutsche Telekom" "DTEGY"
add_alias "SoftBank Group" "SoftBank"
add_alias "SoftBank Group" "SFTBY"
add_alias "NTT" "Nippon Telegraph & Telephone"
add_alias "NTT" "NTTYY"
add_alias "Orange" "Orange S.A."
add_alias "Orange" "ORAN"
add_alias "Telefónica" "Telefonica"
add_alias "Telefónica" "TEF"
add_alias "América Móvil" "America Movil"
add_alias "América Móvil" "AMX"
add_alias "Bharti Airtel" "Airtel"
add_alias "Bharti Airtel" "BHARTIARTL"
add_alias "Vodafone" "Vodafone Group"
add_alias "Vodafone" "VOD"

# -------- MANUFACTURING & INDUSTRIAL --------
add_alias "Boeing" "The Boeing Company"
add_alias "Boeing" "BA"
add_alias "Caterpillar" "Caterpillar Inc"
add_alias "Caterpillar" "CAT"
add_alias "3M" "3M Company"
add_alias "3M" "MMM"
add_alias "General Electric" "General Electric Company"
add_alias "General Electric" "GE"
add_alias "Honeywell" "Honeywell International Inc"
add_alias "Honeywell" "HON"
add_alias "Lockheed Martin" "Lockheed Martin Corporation"
add_alias "Lockheed Martin" "LMT"
add_alias "Raytheon" "Raytheon Technologies Corporation"
add_alias "Raytheon" "RTX"
add_alias "Northrop Grumman" "Northrop Grumman Corporation"
add_alias "Northrop Grumman" "NOC"
add_alias "Deere" "Deere & Company"
add_alias "Deere & Company" "John Deere"
add_alias "Deere" "DE"
add_alias "Emerson Electric" "Emerson Electric Co"
add_alias "Emerson Electric" "EMR"
add_alias "Johnson Controls" "Johnson Controls International plc"
add_alias "Johnson Controls" "JCI"
add_alias "Illinois Tool Works"  "Illinois Tool Works Inc"
add_alias "Illinois Tool Works" "ITW"
add_alias "ABB" "ABB Ltd"
add_alias "ABB" "ABB"
add_alias "Eaton" "Eaton Corporation"
add_alias "Eaton" "ETN"
add_alias "General Dynamics" "General Dynamics Corporation"
add_alias "General Dynamics" "GD"
add_alias "L3Harris Technologies" "L3Harris"
add_alias "L3Harris Technologies" "LHX"
add_alias "Textron" "Textron Inc"
add_alias "Textron" "TXT"
add_alias "Parker-Hannifin" "Parker Hannifin Corporation"
add_alias "Parker-Hannifin" "PH"
add_alias "Ingersoll Rand" "Ingersoll Rand Inc"
add_alias "Ingersoll Rand" "IR"
add_alias "Cummins" "Cummins Inc"
add_alias "Cummins" "CMI"
add_alias "Otis Worldwide" "Otis Elevator Company"
add_alias "Otis Worldwide" "OTIS"
add_alias "Carrier Global" "Carrier"
add_alias "Carrier Global" "CARR"
add_alias "Stanley Black & Decker" "Stanley Black and Decker"
add_alias "Stanley Black & Decker" "SWK"
add_alias "Xylem" "Xylem Inc"
add_alias "Xylem" "XYL"
add_alias "Rockwell Automation" "Rockwell"
add_alias "Rockwell Automation" "ROK"
add_alias "Fortive" "Fortive Corporation"
add_alias "Fortive" "FTV"
add_alias "Paccar" "PACCAR Inc"
add_alias "Paccar" "PCAR"
add_alias "Dover" "Dover Corporation"
add_alias "Dover" "DOV"
add_alias "Huntington Ingalls Industries" "HII"
add_alias "Huntington Ingalls Industries" "Huntington Ingalls"

# -------- INTERNATIONAL COMPANIES --------
add_alias "Samsung" "Samsung Electronics Co Ltd"
add_alias "Samsung" "SSNLF"
add_alias "Royal Dutch Shell" "Shell plc"
add_alias "Royal Dutch Shell" "Shell"
add_alias "Royal Dutch Shell" "SHEL"
add_alias "BP" "BP plc"
add_alias "BP" "British Petroleum"
add_alias "BP" "BP"
add_alias "TotalEnergies" "TotalEnergies SE"
add_alias "TotalEnergies" "Total"
add_alias "TotalEnergies" "TTE"
add_alias "HSBC" "HSBC Holdings plc"
add_alias "HSBC" "HSBC"
add_alias "Allianz" "Allianz SE"
add_alias "Allianz" "ALIZY"
add_alias "Siemens" "Siemens AG"
add_alias "Siemens" "SIEGY"
add_alias "Nestlé" "Nestlé S.A."
add_alias "Nestlé" "NSRGY"
add_alias "Unilever" "Unilever plc"
add_alias "Unilever" "UL"
add_alias "Sony" "Sony Group Corporation"
add_alias "Sony" "SONY"
add_alias "Panasonic" "Panasonic Holdings Corporation"
add_alias "Panasonic" "PCRFY"
add_alias "LG" "LG Electronics Inc"
add_alias "LG" "LGEIY"
add_alias "Alibaba" "Alibaba Group Holding Limited"
add_alias "Alibaba" "BABA"
add_alias "Tencent" "Tencent Holdings Ltd"
add_alias "Tencent" "TCEHY"
add_alias "China Mobile" "China Mobile Limited"
add_alias "China Mobile" "CHL"
add_alias "ICBC" "Industrial and Commercial Bank of China"
add_alias "ICBC" "IDCBY"
add_alias "China Construction Bank" "CCB"
add_alias "China Construction Bank" "CICHY"
add_alias "Agricultural Bank of China" "ABC"
add_alias "Agricultural Bank of China" "ACGBY"
add_alias "Ping An Insurance" "Ping An Insurance Group"
add_alias "Ping An Insurance" "PNGAY"
add_alias "Mitsubishi" "Mitsubishi Corporation"
add_alias "Mitsubishi" "MSBHF"
add_alias "Mitsui" "Mitsui & Co Ltd"
add_alias "Mitsui" "MITSY"
add_alias "AstraZeneca" "AstraZeneca plc"
add_alias "AstraZeneca" "AZN"
add_alias "Novartis" "Novartis AG"
add_alias "Novartis" "NVS"
add_alias "Roche" "Roche Holding AG"
add_alias "Roche" "RHHBY"
add_alias "Bayer" "Bayer AG"
add_alias "Bayer" "BAYRY"
add_alias "BASF" "BASF SE"
add_alias "BASF" "BASFY"
add_alias "Sanofi" "Sanofi S.A."
add_alias "Sanofi" "SNY"
add_alias "Nintendo" "Nintendo Co Ltd"
add_alias "Nintendo" "NTDOY"
add_alias "Hon Hai Precision" "Foxconn"
add_alias "Hon Hai Precision" "HNHPF"
add_alias "CNOOC" "China National Offshore Oil Corporation"
add_alias "CNOOC" "CEO"
add_alias "Sinopec" "China Petroleum & Chemical Corporation"
add_alias "Sinopec" "SNP"
add_alias "PetroChina" "PetroChina Company Limited"
add_alias "PetroChina" "PTR"
add_alias "BHP Group" "BHP"
add_alias "BHP Group" "BHP"
add_alias "Rio Tinto" "Rio Tinto Group"
add_alias "Rio Tinto" "RIO"
add_alias "Glencore" "Glencore plc"
add_alias "Glencore" "GLNCY"
add_alias "Anglo American" "Anglo American plc"
add_alias "Anglo American" "NGLOY"
add_alias "Gazprom" "Gazprom PAO"
add_alias "Gazprom" "OGZPY"
add_alias "Lukoil" "PJSC Lukoil"
add_alias "Lukoil" "LUKOY"
add_alias "Saudi Aramco" "Saudi Arabian Oil Company"
add_alias "Saudi Aramco" "2222.SR"
add_alias "Reliance Industries" "Reliance Industries Limited"
add_alias "Reliance Industries" "RELIANCE"
add_alias "HDFC Bank" "HDFC Bank Limited"
add_alias "HDFC Bank" "HDB"
add_alias "Tata Consultancy Services" "TCS"
add_alias "Tata Consultancy Services" "TCS"
add_alias "Infosys" "Infosys Limited"
add_alias "Infosys" "INFY"
add_alias "Taiwan Semiconductor" "Taiwan Semiconductor Manufacturing Company"
add_alias "Taiwan Semiconductor" "TSMC"
add_alias "Taiwan Semiconductor" "TSM"
add_alias "SK Hynix" "SK Hynix Inc"
add_alias "SK Hynix" "HXSCL"
add_alias "ASML Holding" "ASML"
add_alias "ASML Holding" "ASML"
add_alias "LVMH"  "LVMH Moët Hennessy Louis Vuitton"
add_alias "LVMH" "Louis Vuitton"
add_alias "LVMH" "LVMUY"
add_alias "L'Oréal" "L'Oreal"
add_alias "L'Oréal" "LRLCY"
add_alias "Kering" "Kering S.A."
add_alias "Kering" "PPRUY"
add_alias "Hermès" "Hermes"
add_alias "Hermès" "HESAY"
add_alias "Adidas" "Adidas AG"
add_alias "Adidas" "ADDYY"
add_alias "Puma" "Puma SE"
add_alias "Puma" "PMMAF"

# -------- ADDITIONAL MAJOR COMPANIES --------
add_alias "Berkshire Hathaway" "Berkshire Hathaway Inc"
add_alias "Berkshire Hathaway" "BRK.A"
add_alias "Berkshire Hathaway" "BRK.B"
add_alias "UPS" "United Parcel Service Inc"
add_alias "UPS" "United Parcel Service"
add_alias "UPS" "UPS"
add_alias "FedEx" "FedEx Corporation"
add_alias "FedEx" "FDX"
add_alias "Uber" "Uber Technologies Inc"
add_alias "Uber" "UBER"
add_alias "Lyft" "Lyft Inc"
add_alias "Lyft" "LYFT"
add_alias "DoorDash" "DoorDash Inc"
add_alias "DoorDash" "DASH"
add_alias "Netflix" "Netflix Inc"
add_alias "Netflix" "NFLX"
add_alias "Walt Disney" "The Walt Disney Company"
add_alias "Disney" "The Walt Disney Company"
add_alias "Walt Disney" "DIS"
add_alias "Disney" "DIS"
add_alias "Warner Bros. Discovery" "Warner Bros Discovery Inc"
add_alias "Warner Bros. Discovery" "WBD"
add_alias "Paramount" "Paramount Global"
add_alias "Paramount" "ViacomCBS"
add_alias "Paramount" "PARA"
add_alias "Airbnb" "Airbnb Inc"
add_alias "Airbnb" "ABNB"
add_alias "Spotify" "Spotify Technology S.A."
add_alias "Spotify" "SPOT"
add_alias "Booking Holdings" "Booking.com"
add_alias "Booking Holdings" "BKNG"
add_alias "Expedia" "Expedia Group Inc"
add_alias "Expedia" "EXPE"
add_alias "Marriott" "Marriott International Inc"
add_alias "Marriott" "MAR"
add_alias "Hilton" "Hilton Worldwide Holdings Inc"
add_alias "Hilton" "HLT"
add_alias "Waste Management" "Waste Management Inc"
add_alias "Waste Management" "WM"
add_alias "Kimberly-Clark" "Kimberly-Clark Corporation"
add_alias "Kimberly-Clark" "KMB"
add_alias "Colgate-Palmolive" "Colgate-Palmolive Company"
add_alias "Colgate-Palmolive" "CL"
add_alias "DuPont" "DuPont de Nemours Inc"
add_alias "DuPont" "DD"
add_alias "Dow" "Dow Inc"
add_alias "Dow" "DOW"
add_alias "Micron" "Micron Technology Inc"
add_alias "Micron" "MU"
add_alias "Applied Materials" "Applied Materials Inc"
add_alias "Applied Materials" "AMAT"
add_alias "Lam Research" "Lam Research Corporation"
add_alias "Lam Research" "LRCX"
add_alias "Broadcom" "Broadcom Inc"
add_alias "Broadcom" "AVGO"
add_alias "Accenture" "Accenture plc"
add_alias "Accenture" "ACN"
add_alias "Amcor" "Amcor plc"
add_alias "Amcor" "AMCR"
add_alias "Air Products and Chemicals" "Air Products"
add_alias "Air Products and Chemicals" "APD"
add_alias "Weyerhaeuser" "Weyerhaeuser Company"
add_alias "Weyerhaeuser" "WY"
add_alias "International Paper" "International Paper Company"
add_alias "International Paper" "IP"
add_alias "Paychex" "Paychex Inc"
add_alias "Paychex" "PAYX"
add_alias "eBay" "eBay Inc"
add_alias "eBay" "EBAY"
add_alias "Etsy" "Etsy Inc"
add_alias "Etsy" "ETSY"
add_alias "Pinterest" "Pinterest Inc"
add_alias "Pinterest" "PINS"
add_alias "Snap" "Snap Inc"
add_alias "Snap" "Snapchat"
add_alias "Snap" "SNAP"
add_alias "Atlassian" "Atlassian Corporation"
add_alias "Atlassian" "TEAM"

echo "Completed adding organization aliases"
