[package]
name = "argus"
version = "0.4.4"
edition = "2021"

[dependencies]
chrono = "0.4"
emailmessage = "0.2"
ollama-rs = "0.1.9"
readability = "0.3"
reqwest = "0.12"
rss = "2.0"
rusqlite = "0.31"
serde_json = "1.0"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
