[package]
name = "argus"
version = "0.3.3"
edition = "2021"

[dependencies]
chrono = "0.4"
emailmessage = "0.2"
ollama-rs = "0.1.9"
readability = "0.3"
reqwest = "0.12"
rss = "2.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
